### ISSUE TITLE
Getting Started Example don't run

### ISSUE THREAD

**Issue by esauvage** [STAMP-project/dspot#127]
`mvn exec:java -Dexec.mainClass="fr.inria.stamp.Main" -Dexec.args="--example"`
gives an error.
Here is the error message:
`java.lang.RuntimeException: java.util.regex.PatternSyntaxException: Unexpected i
nternal error near index 1
\
 ^
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error nea
r index 1
\
 ^`

**Comment by danglotb** [comment]
Hello @esauvage ,

thanks, and sorry for the delay of my answer.

Did you manage to run the test suite?

I am working on the issue, it seems that the command-line bug.

**Comment by esauvage** [comment]
No. Can't have anything running. I'm trying on a project of my own, got maybe the same problem.

**Comment by danglotb** [comment]
Could you try to do:
```
mvn clean package -DskipTests
```
then run
```
java -jar target/dspot-1.0.0-jar-with-dependencies.jar --example
```

> I'm trying on a project of my own, got maybe the same problem.

If the command above works on the example, i suggest you to use the jar instead of maven. On my side, i have issue when i try to run with maven, but not with the jar.

I keep going to search and fix the problem. Also for the suite test, I'm building a new option to put the verbose mode on.

**Comment by esauvage** [comment]
Here is the result : 

src/test/resources/test-projects
Exception in thread "main" java.lang.RuntimeException:
java.util.regex.PatternSy
ntaxException: Unexpected internal error near index 1
\
 ^
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal
error nea
r index 1
\
 ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:94)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:84)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:63)
        at fr.inria.stamp.Main.runExample(Main.java:103)
        ... 2 more 

Le 16-06-2017 11:38, Benjamin DANGLOT a écrit :

> Could you try to do:
> 
> mvn clean package -DskipTests
> 
> then run
> 
> java -jar target/dspot-1.0.0-jar-with-dependencies.jar --example
> 
>> I'm trying on a project of my own, got maybe the same problem.
> 
> If the command above works on the example, i suggest you to use the jar instead of maven. On my side, i have issue when i try to run with maven, but not with the jar. 
> 
> I keep going to search and fix the problem. Also for the suite test, I'm building a new option to put the verbose mode on. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/STAMP-project/dspot/issues/127#issuecomment-308981423
[2]

**Comment by danglotb** [comment]
According to the stack trace, this [line](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/diversify/dspot/DSpot.java#L93) is responsible of the error.

Do you override your separator? Which OS are you using?

Since I do not have the error, I would you to checkout the branch fix-file-system, and retry to run the example.

At the root of DSpot, type:
```
git remote add bdanglot http://github.com/danglotb/dspot.git
git fetch bdanglot
git checkout fix-file-system
mvn clean package -DskipTests
java -jar target/dspot-1.0.0-jar-with-dependencies.jar --example
```

I changed the `System.getProperty("file.separator")` by `FileSystems.getDefault().getSeparator()`

**Comment by esauvage** [comment]
I'm on Windows, as you may have guessed.
The fix didn't change the output.

**Comment by danglotb** [comment]
Ok, my bad. 

For sake of portability, I used the property of the file system. But the splitted string is in the .properties and does not use necessary file system property.

Could please retry? I hope it will also fix your test.

I'm doing a pull request to fix this.

**Comment by esauvage** [comment]
Well, if I understand well, now the same error is elsewhere:
`Exception in thread "main" java.lang.RuntimeException: java.util.regex.PatternSy
ntaxException: Unexpected internal error near index 1
\
 ^
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error nea
r index 1
\
 ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:100)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:91)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:70)
        at fr.inria.stamp.Main.runExample(Main.java:103)
        ... 2 more`

**Comment by danglotb** [comment]
No, you should have [this](https://github.com/danglotb/dspot/commit/954bfe32ac74e81a795a8ebb81bd44af7e775aab#diff-8967f1330b3021e4b5bafcd9cdbf38ccR100)

**Comment by esauvage** [comment]
I'm sorry:
`00:06 DEBUG: timeOut init: 3
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgument
Exception: URI is not hierarchical
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(Unknown Source)
        at fr.inria.diversify.dspot.AmplificationHelper.lambda$getDependenciesOf
$12(AmplificationHelper.java:218)
        at java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Sour
ce)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source
)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.reduce(Unknown Source)
        at fr.inria.diversify.dspot.AmplificationHelper.getDependenciesOf(Amplif
icationHelper.java:216)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:127)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:91)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:70)
        at fr.inria.stamp.Main.runExample(Main.java:103)
        ... 2 more`

**Comment by danglotb** [comment]
Hello,

I updated the branch, it should be ok now.

**Comment by esauvage** [comment]
It gets better. I didn't find where the "C" was defined to add the colon.
00:00 DEBUG: run maven, phase: [clean, test, -DskipTests], timeout -1
00:02 DEBUG: [INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building test-projects 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example --
-
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ex
ample ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ example
 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ example ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.343 s
[INFO] Finished at: 2017-06-19T10:36:51+02:00
[INFO] Final Memory: 15M/206M
[INFO] ------------------------------------------------------------------------

00:03 DEBUG: timeOut init: 3
00:03 DEBUG: timeOut init: 12
00:03 DEBUG: run maven, phase: [dependency:build-classpath, -Dmdep.outputFile=cp
], timeout -1
00:06 DEBUG: timeOut init: 3
Exception in thread "main" java.lang.RuntimeException: spoon.compiler.InvalidCla
ssPathException: C does not exist, it is not a valid folder
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: spoon.compiler.InvalidClassPathException: C does not exist, it is not
 a valid folder
        at spoon.support.StandardEnvironment.verifySourceClasspath(StandardEnvir
onment.java:410)
        at spoon.support.StandardEnvironment.setSourceClasspath(StandardEnvironm
ent.java:400)
        at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.setSourceClasspath(J
DTBasedSpoonCompiler.java:309)
        at fr.inria.diversify.dspot.support.DSpotCompiler.getSpoonModelOf(DSpotC
ompiler.java:91)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:124)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:84)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:63)
        at fr.inria.stamp.Main.runExample(Main.java:103)
        ... 2 more

**Comment by danglotb** [comment]
Hi, 

I look deeper for all usage of path in DSpot.

The C come from your disk (usually C: is the letter of the system). In DSpot, we splitted the path with ":", while on windows, the path separator is ;

I fix it. Could you try again?

I am sorry about this, and thank you for helping us!

**Comment by esauvage** [comment]
And here is the result:
00:00 DEBUG: run maven, phase: [clean, test, -DskipTests], timeout -1
00:02 DEBUG: [INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building test-projects 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example --
-
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ex
ample ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ example
 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ example ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.304 s
[INFO] Finished at: 2017-06-19T12:02:57+02:00
[INFO] Final Memory: 15M/204M
[INFO] ------------------------------------------------------------------------

00:03 DEBUG: timeOut init: 3
00:03 DEBUG: timeOut init: 12
00:03 DEBUG: run maven, phase: [dependency:build-classpath, -Dmdep.outputFile=cp
], timeout -1
00:06 DEBUG: timeOut init: 3
Exception in thread "main" java.lang.RuntimeException: spoon.SpoonException: jav
a.io.IOException: La syntaxe du nom de fichier, de répertoire ou de volume est i
ncorrecte
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: spoon.SpoonException: java.io.IOException: La syntaxe du nom de fichi
er, de répertoire ou de volume est incorrecte
        at spoon.support.compiler.FileSystemFile.<init>(FileSystemFile.java:45)
        at spoon.Launcher.addInputResource(Launcher.java:160)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Sour
ce)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at fr.inria.diversify.dspot.support.DSpotCompiler.getSpoonModelOf(DSpotC
ompiler.java:88)
        at fr.inria.diversify.dspot.support.DSpotCompiler.<init>(DSpotCompiler.j
ava:28)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:135)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:84)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:63)
        at fr.inria.stamp.Main.runExample(Main.java:103)
        ... 2 more
Caused by: java.io.IOException: La syntaxe du nom de fichier, de répertoire ou d
e volume est incorrecte
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at java.io.File.getCanonicalFile(Unknown Source)
        at spoon.support.compiler.FileSystemFile.<init>(FileSystemFile.java:43)
        ... 11 more

**Comment by danglotb** [comment]
Could you retry please?

**Comment by esauvage** [comment]
Here you are :
00:00 DEBUG: run maven, phase: [clean, test, -DskipTests], timeout -1
00:02 DEBUG: [INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building test-projects 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example --
-
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ex
ample ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Etienne\CodeOW2\dspot\tmpDir
\tmp\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ example
 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Etienne\CodeOW2\dspot\tmpDir\tmp\targ
et\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ example ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.278 s
[INFO] Finished at: 2017-06-19T15:55:42+02:00
[INFO] Final Memory: 15M/206M
[INFO] ------------------------------------------------------------------------

00:03 DEBUG: timeOut init: 3
00:03 DEBUG: timeOut init: 12
00:03 DEBUG: run maven, phase: [dependency:build-classpath, -Dmdep.outputFile=cp
], timeout -1
00:06 DEBUG: timeOut init: 3
00:08 DEBUG: elapsedTime 25

======= REPORT =======
Branch Coverage Selector:
Initial coverage: 0,00%
There is 0 unique path in the original test suite
The amplification results with 0 new tests
The branch coverage obtained is: NaN%
There is 0 new unique path


Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerExce
ption
        at fr.inria.stamp.Main.runExample(Main.java:106)
        at fr.inria.stamp.JSAPOptions.parse(JSAPOptions.java:56)
        at fr.inria.stamp.Main.main(Main.java:21)
Caused by: java.lang.NullPointerException
        at fr.inria.diversify.dspot.selector.BranchCoverageTestSelector.report(B
ranchCoverageTestSelector.java:198)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:227)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:215)
        at fr.inria.stamp.Main.runExample(Main.java:104)
        ... 2 more

**Comment by danglotb** [comment]
Hello, 

I could get a Windows on my side. I'll fix it and tell you when it is done. It will be much more easier for both of us.

Thank you for taking time for DSpot. :)

**Comment by esauvage** [comment]
Hello,

Great. please keep me informed.

**Comment by danglotb** [comment]
On my Windows, I could the test suit.

The example is still buggy with maven, could you run it with the jar with:

```
java -jar target/dspot-1.0.0-jar-with-dependencies.jar --example
```

**Comment by esauvage** [comment]
It works ! Thank you !
