### ISSUE TITLE
NullPointerException thrown by fr.inria.diversify.dspot.DSpot.lambda$amplifyTest

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#181]
Trying to use dspot on sat4j with the following property file:

```
#relative path to the project root from dspot project
project=.
targetModule=org.sat4j.core
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#filter used to amplify specific test cases
filter=org.sat4j.core.*
#path to the output folder
outputDirectory=output
configPath=sat4j.properties
```

Command line:

```
java -jar ../dspot/target/dspot-1.0.0-jar-with-dependencies.jar --path-to-properties ./sat4j.properties --iteration 2 --test org.sat4j.SingleSolutionTest --cases test --amplifiers NumberLiteralAmplifier --test-criterion PitMutantScoreSelector
```

Exception thrown:

```
00:02 DEBUG: Selected Maven automatic builder.
00:00 INFO: maven home found at /opt/apache-maven-3.5.0/
00:02 INFO: run maven dependency:build-classpath -Dmdep.outputFile=cp
00:27 INFO: run maven test -DskipTests org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=org.sat4j.core.* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -Dmutators=ALL  
01:56 DEBUG: The original test suite kill 333 / 1138
Exception in thread "main" java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at fr.inria.stamp.Main.amplifyOne(Main.java:84)
	at fr.inria.stamp.Main.lambda$run$0(Main.java:55)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at fr.inria.stamp.Main.run(Main.java:53)
	at fr.inria.stamp.Main.main(Main.java:27)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at fr.inria.diversify.dspot.DSpot.lambda$amplifyTest$4(DSpot.java:268)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:270)
	at fr.inria.stamp.Main.amplifyOne(Main.java:81)
```

**Comment by danglotb** [comment]
Hello @slauriere 

According to the stack trace, DSpot does not find the test class or the test method.

Are you sure that the test class `org.sat4j.SingleSolutionTest ` exists and contains 
the test method named `test`.

```
--path-to-properties ./sat4j.properties \
--iteration 2 \
--test org.sat4j.SingleSolutionTest \
--cases test \
--amplifiers NumberLiteralAmplifier \
--test-criterion PitMutantScoreSelector 
```

Also, in your properties file the value of `targetModule` seems wrong:
`targetModule=org.sat4j.core`

You should put the path to the target module and not the qualified name.

DSpot concatenate both values of Project and targetModule, to build the path to the targetModule:
`Project+targetModule`.

In your case, this gives `./org.sat4j.core/`and I think this is wrong.

Thank you very much for trying dspot.

Cheers.

**Comment by slauriere** [comment]
Thank you @danglotb, I replaced ```--cases test``` by ```--cases testHasASingleSolution``` and it worked fine. Got no amplified test though.
