### ISSUE TITLE
fail to execute on seedstack: TypeMismatch issue

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#182]
Trying to execute dspot on [SeedStack](https://github.com/seedstack) with the following command:

```
java -jar ../dspot/target/dspot-1.0.0-jar-with-dependencies.jar --path-to-properties ./seed.properties --iteration 2 --test org.seedstack.seed.core.internal.configuration.ConfigurationPluginTest --cases nameTest --amplifiers NumberLiteralAmplifier --test-criterion PitMutantScoreSelector --verbose
```

Property file:

```
#relative path to the project root from dspot project
project=../seed/
targetModule=core/
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#filter used to amplify specific test cases
filter=org.seedstack.seed.*
#path to the output folder
outputDirectory=output
configPath=seed.properties
```

The following error is thrown:

```
Exception in thread "main" spoon.compiler.ModelBuildingException: Type mismatch: cannot convert from Class<capture#4-of ? extends ErrorCode> to Class<Object> at /home/sysop/stamp/seed/tmpDir/tmp/core/src/main/java/org/seedstack/seed/core/internal/diagnostic/tool/ErrorsTool.java:50
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:579)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:560)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:121)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:102)
	at spoon.Launcher.buildModel(Launcher.java:700)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:120)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:143)
	at fr.inria.stamp.Main.run(Main.java:44)
	at fr.inria.stamp.Main.main(Main.java:27)
```

**Comment by monperrus** [comment]
This is probably because Dspot inherits the requirements of Spoon which states that the program has
to be compilable with Eclipse JDT. Unfortunately, Eclipse JDT and the Oracle java compiler are not
100% compatible, meaning that some programs compile with the oracle compiler and not Eclipse.
Consequently Spoon fails, and Dspot fails.

The solution is to make SeedStack compile with Eclipse JDT by manually modifying it (usually a small
modification).

**Comment by monperrus** [comment]
Closing this one (see comment above for a workaround)
