### ISSUE TITLE
NullPointer at PitMutantScoreSelector.lambda$selectToKeep

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#183]
While running dspot on sat4j:

```
java -jar ../dspot/target/dspot-1.0.0-jar-with-dependencies.jar --path-to-properties ./sat4j.properties --iteration 2 --test org.sat4j.SingleSolutionTest --cases testHasASingleSolution --amplifiers NumberLiteralAmplifier --test-criterion PitMutantScoreSelector
```

with the following property file:
```
#relative path to the project root from dspot project
project=.
targetModule=org.sat4j.core
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#filter used to amplify specific test cases
filter=org.sat4j.core.*
#path to the output folder
outputDirectory=output
configPath=sat4j.properties
```

I get the following error:

```
00:55 DEBUG: 6 test method(s) has been successfully generated
00:55 INFO: run maven test -DskipTests org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=org.sat4j.core.* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DtargetTests=org.sat4j.SingleSolutionTest  -Dmutators=ALL 
01:22 DEBUG: 1138 mutants has been generated (1138)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at fr.inria.stamp.Main.amplifyOne(Main.java:84)
	at fr.inria.stamp.Main.lambda$run$0(Main.java:55)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at fr.inria.stamp.Main.run(Main.java:53)
	at fr.inria.stamp.Main.main(Main.java:27)
Caused by: java.lang.NullPointerException
	at fr.inria.diversify.mutant.pit.PitResult.getMethod(PitResult.java:66)
	at fr.inria.diversify.mutant.pit.PitResult.getMethod(PitResult.java:69)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.lambda$selectToKeep$5(PitMutantScoreSelector.java:109)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.selectToKeep(PitMutantScoreSelector.java:108)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:129)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:84)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:278)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:267)
	at fr.inria.stamp.Main.amplifyOne(Main.java:81)
```

**Comment by monperrus** [comment]
can we close this issue?

**Comment by slauriere** [comment]
closing this issue indeed
