### ISSUE TITLE
Running dspot on sat4j raises error

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#251]
**Issue type:** possible misuse
**Description:** error thrown while applying dspot to sat4j
**Steps to reproduce:** 
1) Checkout the sat4j project from https://gitlab.ow2.org/sat4j/sat4j and build it
2) Create the following properties file:
```
#relative path to the project root from dspot project
project=sat4j/org.sat4j.core
#relative path to the source project from the project properties
src=sat4j/org.sat4j.core/src/main/java
#relative path to the test source project from the project properties
testSrc=sat4j/org.sat4j.core/src/test/java
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.sat4j.core*
```
3) Run the following command line:
``java -cp target/dspot-1.0.0-jar-with-dependencies.jar fr.inria.stamp.Main --verbose --path-to-properties sat4j.properties``
4) Dspot outputs the following error:
```
java -cp target/dspot-1.0.0-jar-with-dependencies.jar fr.inria.stamp.Main --verbose --path-to-properties sat4j.properties
2017-11-17 10:10:05,000 INFO fr.inria.diversify.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2017-11-17 10:10:05,142 DEBUG spoon.Launcher - building sources: []
2017-11-17 10:10:05,213 DEBUG spoon.Launcher - built in 71 ms
2017-11-17 10:10:05,213 DEBUG spoon.Launcher - building templates: []
2017-11-17 10:10:05,213 DEBUG spoon.Launcher - built in 0 ms
2017-11-17 10:10:05,214 DEBUG spoon.Launcher - model built in 72
2017-11-17 10:10:05,216 DEBUG spoon.Launcher - compiling sources: []
2017-11-17 10:10:05,283 DEBUG spoon.Launcher - compile args: [-encoding, UTF-8, -cp, /home/slauriere/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/slauriere/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/slauriere/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:target/dspot/dependencies/:, -d, /home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/org.sat4j.core/target/classes, -1.8, -proc:none, -preserveAllLocals, -noExit, -enableJavadoc, .]
2017-11-17 10:10:05,536 DEBUG spoon.Launcher - compiled in 320 ms
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - building sources: []
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - built in 0 ms
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - building templates: []
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - built in 0 ms
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - model built in 0
2017-11-17 10:10:05,540 DEBUG spoon.Launcher - compiling sources: []
2017-11-17 10:10:05,541 DEBUG spoon.Launcher - compile args: [-encoding, UTF-8, -cp, /home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/org.sat4j.core/target/classes:/home/slauriere/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/slauriere/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/slauriere/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:target/dspot/dependencies/:, -d, /home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/org.sat4j.core/target/test-classes, -1.8, -proc:none, -preserveAllLocals, -noExit, -enableJavadoc, .]
2017-11-17 10:10:05,625 DEBUG spoon.Launcher - compiled in 84 ms
2017-11-17 10:10:05,642 INFO fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder - run maven  org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=org.sat4j.core* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ 
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.ow2.sat4j:org.ow2.sat4j.core:jar:2.3.6-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.ow2.sat4j:org.ow2.sat4j.pom:2.3.6-SNAPSHOT (/home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/pom.xml) points at fr.inria.stamp:dspot-parent instead of org.ow2:ow2, please verify your project structure @ org.ow2.sat4j:org.ow2.sat4j.pom:2.3.6-SNAPSHOT, /home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/pom.xml, line 5, column 10
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SAT4J core 2.3.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- pitest-maven:1.2.2:mutationCoverage (default-cli) @ org.ow2.sat4j.core ---
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found plugin : Kotlin junk mutations filter
[INFO] Found plugin : Static initializer code detector plugin
[INFO] Found plugin : Static initializer filter plugin
[INFO] Found plugin : Excluded annotations plugin
[INFO] Found plugin : Inlined finally block filter plugin
[INFO] Found plugin : Try with resources filter
[INFO] Found plugin : Logging calls filter
[INFO] Found plugin : Infinite for loop filter
[INFO] Found plugin : Long running iterator loop filter
[INFO] Found shared classpath plugin : Default mutation engine
[INFO] Adding org.pitest:pitest to SUT classpath
[INFO] Mutating from /home/slauriere/OW2/Collabs/STAMP/dspot/sat4j/org.sat4j.core/target/classes
[INFO] Will read and write history at /tmp/org.ow2.sat4j.org.ow2.sat4j.core.2.3.6-SNAPSHOT_pitest_history.bin
10:10:09 AM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
10:10:09 AM PIT >> INFO : Sending 0 test classes to minion
10:10:09 AM PIT >> INFO : Sent tests to minion
10:10:09 AM PIT >> INFO : MINION : 10:10:09 AM PIT >> INFO : Checking environment
10:10:09 AM PIT >> INFO : Found  0 tests
10:10:09 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0
10:10:09 AM PIT >> INFO : 0 tests received

10:10:09 AM PIT >> INFO : Calculated coverage in 0 seconds.
10:10:09 AM PIT >> INFO : Created  0 mutation test units
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.590 s
[INFO] Finished at: 2017-11-17T10:10:09+01:00
[INFO] Final Memory: 14M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.2:mutationCoverage (default-cli) on project org.ow2.sat4j.core: Execution default-cli of goal org.pitest:pitest-maven:1.2.2:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:180)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:59)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:102)
	at fr.inria.stamp.Main.run(Main.java:49)
	at fr.inria.stamp.Main.main(Main.java:32)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:177)
	... 4 more

```

**Comment by danglotb** [comment]
Hello @slauriere 

I think your properties is wrong.
```properties
#relative path to the source project from the project properties
src=sat4j/org.sat4j.core/src/main/java
#relative path to the test source project from the project properties
testSrc=sat4j/org.sat4j.core/src/test/java
```
Those paths are relative to the value of the properties `project`. **DSpot** computes `$project + / + $src` to access to the folder of sources (same for the test sources).
It should be:
```properties
src=src/main/java
testSrc=src/test/java
```

On my side, I had to increase the time before Time Out when **DSpot** runs tests with the option `--timeOut 50000` (`-v 50000`).

I also see that tests are using resources. We have to give the path (also relative to `project`) to let **DSpot** know about it. Add the following properties:

```properties
srcResources=src/main/resources/
testResources=src/test/testfiles/:src/test/java/
```

The whole properties file would be:
```properties
#relative path to the project root from dspot project
project=org.sat4j.core/
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
srcResources=src/main/resources/
testResources=src/test/testfiles/:src/test/java/
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.sat4j.core*
```

Launch from sat4j (root directory of the clone project) with:

`java -jar target/dspot-1.0.0-jar-with-dependencies.jar --verbose --path-to-properties sat4j.properties --timeOut 50000`

**Comment by slauriere** [comment]
Thanks a lot @danglotb this way it works!
