### ISSUE TITLE
perf: java.lang.OutOfMemoryError when amplification the whole project (works with one-be-one amplification)

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/dspot#253]
**Issue Type**: bug/isuse
**Description**: 
Java heap space when I ran a set of Test:

```
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jdt.internal.compiler.util.Util.getInputStreamAsCharArray(Util.java:623)
	at org.eclipse.jdt.internal.compiler.util.Util.getFileCharContent(Util.java:420)
	at org.eclipse.jdt.internal.compiler.batch.CompilationUnit.getContents(CompilationUnit.java:85)
	at org.eclipse.jdt.internal.compiler.batch.BatchCompilerRequestor.acceptResult(BatchCompilerRequestor.java:38)
	at spoon.support.compiler.jdt.JDTBatchCompiler$1.acceptResult(JDTBatchCompiler.java:89)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:581)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:468)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at fr.inria.diversify.dspot.support.DSpotJDTBatchCompiler.performCompilation(DSpotJDTBatchCompiler.java:53)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1767)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:79)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compileAndGetProbs(DSpotCompiler.java:86)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:61)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compileAndRun(TestCompiler.java:40)
	at fr.inria.diversify.dspot.Amplification.compileAndRunTests(Amplification.java:224)
	at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:150)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:75)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:174)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157)
	at fr.inria.diversify.dspot.DSpot$$Lambda$38/269853881.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jdt.internal.compiler.util.Util.getInputStreamAsCharArray(Util.java:623)
	at org.eclipse.jdt.internal.compiler.util.Util.getFileCharContent(Util.java:420)
	at org.eclipse.jdt.internal.compiler.batch.CompilationUnit.getContents(CompilationUnit.java:85)
	at org.eclipse.jdt.internal.compiler.batch.BatchCompilerRequestor.acceptResult(BatchCompilerRequestor.java:38)
	at spoon.support.compiler.jdt.JDTBatchCompiler$1.acceptResult(JDTBatchCompiler.java:89)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:581)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:468)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at fr.inria.diversify.dspot.support.DSpotJDTBatchCompiler.performCompilation(DSpotJDTBatchCompiler.java:53)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1767)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:79)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compileAndGetProbs(DSpotCompiler.java:86)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:61)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compile(TestCompiler.java:112)
	at fr.inria.diversify.dspot.support.TestCompiler.compileAndRun(TestCompiler.java:40)
	at fr.inria.diversify.dspot.Amplification.compileAndRunTests(Amplification.java:224)
	at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:150)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:75)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:174)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157)
	at fr.inria.diversify.dspot.DSpot$$Lambda$38/269853881.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
```

**Reproducibility**: always 
**Severity**: major 
**Tool**: STAMP dspot Version:latest
**Execution Environment**: Linux Centos7.x86_64 
**Steps to reproduce**:
`
[root@osboxes dspot]# java -jar target/dspot-1.0.0-jar-with-dependencies.jar  -p ../../fiware-cygnus/cygnus-common/fiware.properties -i 1 -t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector
`

**Files**:
properties files:
> #relative path to the project root from dspot project
project=../../fiware-cygnus/cygnus-common
#relative path to the source project from the project properties
src=src/main/java/
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#(optional) path to the output folder, default to "output_diversify"
outputDirectory=fiware-out/
#(optional) filter on the package name containing tests to be amplified ("example" => "example.*")
filter=com.telefonica.iot.cygnus*
#(optional) filter on the package name containing tests to be excluded
#excludedClasses=my.class.TestClass,my.pacakage.*
excludedClasses=CKANBackendImplTest.java,com.telefonica.iot.cygnus.backends.ckan.*
,HDFSBackendImplBinaryTest,com.telefonica.iot.cygnus.backends.hdfs.*
,MySQLBackendImplTest,com.telefonica.iot.cygnus.backends.mysql.*
,PostgreSQLBackendImplTest,com.telefonica.iot.cygnus.backends.postgresql.*
,ManagementInterfaceTest,com.telefonica.iot.cygnus.management.*
,MetricsHandlersTest,com.telefonica.iot.cygnus.management.*
,CygnusMetricsTest,com.telefonica.iot.cygnus.utils.*

TEST to amplified:  [https://github.com/telefonicaid/fiware-cygnus](https://github.com/telefonicaid/fiware-cygnus)

**Relationships**: 
**Reporter**: Fernando Méndez Requena fernando.mendez.external@atos.net

**Comment by danglotb** [comment]
HI @fermenreq 

Thank you for using **DSpot**.

The problem is when **DSpot** tries to compile you project.

Have much memory do you have? 

You may need increase the allocated memory to the JVM by using the corresponding options:

`java -Xms4G -Xmx8G` for instance.

Could please, tell me if this problem occurs at the begin of the amplification, or if **DSpot** has been able to start the amplification?

When trying your use case, I found out some bugs inside **DSpot**, thank you, I'am preparing a PR to fix them.

Thank you!

-- Benjamin.

**Comment by fermenreq** [comment]
Hi  @danglotb

Yes, DSpot start the amplification correctly.
If you execute one by one, DSpot works great. Otherwise if you run all together it’s return the error before I posted 
I execute the command line you said including the options and the behaviour it’s the same 

Thanks in advance

**Comment by danglotb** [comment]
Hi @fermenreq 

I am sorry, but I do not have any solution unless increase the allocated memory to the JVM or amplify tests one by one (or smaller package).

**DSpot** consumes a lot of memory, some optimization could be done (Not sure, but probably) and I invite anyone to look for them.

Cheers.

**Comment by fermenreq** [comment]
Hi @danglotb 

I increase the RAM memory to 5239MB using 2 CPUs and the result its the same before.

Regards

**Comment by monperrus** [comment]
Hi @fermenreq did you put 5G in `-Xms5G`, `-Xmx5G` or both?

**Comment by fermenreq** [comment]
Hi monperrus,

Yes I put like you said and it returns:

`root@osboxes:/home/osboxes/Desktop/STAMP/dspot/dspot# java -Xms5G -jar target/dspot-1.0.2-SNAPSHOT-jar-with-dependencies.jar -p ../../fiware-cygnus/cygnus-common/fiware.properties -i 1 -t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector`

2017-12-05 19:38:36,965 INFO fr.inria.diversify.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2017-12-05 19:38:54,216 INFO fr.inria.diversify.dspot.Amplification - amplification of com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest (1 test)
2017-12-05 19:38:56,345 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting max total connections (50)
2017-12-05 19:38:56,349 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting default max connections per route (10)
2017-12-05 19:38:56,379 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting max total connections (50)
2017-12-05 19:38:56,381 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting default max connections per route (10)
Testing CKANBackendImpl.persist
2017-12-05 19:38:56,530 INFO fr.inria.diversify.dspot.Amplification - update test testCriterion
2017-12-05 19:38:56,530 INFO fr.inria.diversify.dspot.Amplification - Try to add assertions before amplification
2017-12-05 19:38:57,404 WARN fr.inria.stamp.coverage.JacocoExecutor - Some test(s) failed during computation of coverage:
com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest: 
Mockito cannot mock this class: class com.telefonica.iot.cygnus.backends.ckan.CKANCache.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.151-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_151-b12
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.10.0-40-generic


Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
2017-12-05 19:38:58,040 WARN fr.inria.stamp.coverage.JacocoExecutor - Some test(s) failed during computation of coverage:
com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest: 
Mockito cannot mock this class: class com.telefonica.iot.cygnus.backends.ckan.CKANCache.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.151-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_151-b12
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.10.0-40-generic
`Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
    at fr.inria.stamp.Main.amplifyOne(Main.java:94)
    at fr.inria.stamp.Main.lambda$run$0(Main.java:68)
    at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
    at fr.inria.stamp.Main.run(Main.java:64)
    at fr.inria.stamp.Main.main(Main.java:38)
Caused by: java.lang.NullPointerException
    at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.lambda$selectToAmplify$0(JacocoCoverageSelector.java:66)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:73)
    at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:183)
    at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:75)
    at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:187)
    at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:169)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157)
    at fr.inria.stamp.Main.amplifyOne(Main.java:89)
    ... 4 more
`

Thanks in advance!

**Comment by monperrus** [comment]
This is now another error AFAIU.
It seems the OutOfMemoryError is gone. Correct?

**Comment by fermenreq** [comment]
Hi @monperrus , it seems yes. This issue can be closed. 
I'll report the newest one. 

Thanks,

Regards
