### ISSUE TITLE
Failure to run DSpot on WaarpCommon

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#263]
Trying to run DSpot on [WaarpCommon](https://github.com/waarp/WaarpCommon) with the following dspot.properties:

```
#relative path to the project root from dspot project
project=.
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#srcResources=src/main/resources/
#testResources=src/test/resources/
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.waarp.common*
```

And the following command line:

```
java -jar ../dspot/target/dspot-1.0.0-jar-with-dependencies.jar --verbose --path-to-properties dspot.properties --timeOut 50000
```

I get the following error:

```
Exception in thread "main" spoon.compiler.ModelBuildingException: lang cannot be resolved or is not a field at /home/slauriere/OW2/Collabs/STAMP/code/WaarpCommon/WaarpShutdownHook.java:343
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:581)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:562)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.compile(JDTBasedSpoonCompiler.java:157)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:131)
	at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:60)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:85)
	at fr.inria.stamp.Main.run(Main.java:49)
	at fr.inria.stamp.Main.main(Main.java:32)
```

**Comment by danglotb** [comment]
Hello @slauriere 

I could not build WaarpCommon, because of:
```
 Could not resolve dependencies for project Waarp:WaarpCommon:jar:3.0.8: Failure to find Oracle:ojdbc6:jar:6 
```

And I did not find any specific repository. Could you help me to find this dependency?

Thank you.

**Comment by slauriere** [comment]
Thank you @danglotb 

The Oracle JDBC driver is not free software so it not available from the Maven repositories and it has to be installed manually. See https://stamp.ow2.org/bin/view/wiki/Oracle+JDBC for a quick install.

**Comment by danglotb** [comment]
It is because it is using Java 9.

I have to upgrade the version of **Spoon**.

**Comment by slauriere** [comment]
Thanks for the quick feedback.
