### ISSUE TITLE
Failure to run DSpot on Imixs-Workflow core

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#267]
Steps to reproduce:

```
git clone https://github.com/imixs/imixs-workflow/
mvn clean install
```

Run DSpot with the following properties:

```
#relative path to the project root from dspot project
project=imixs-workflow-core
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#srcResources=src/main/resources/
testResources=src/test/resources/
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.imixs.workflow*
```

I get the following error while mvn clean install completes successfully:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.stamp.Main.amplifyAll(Main.java:107)
	at fr.inria.stamp.Main.run(Main.java:56)
	at fr.inria.stamp.Main.main(Main.java:32)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:127)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.selectToKeep(PitMutantScoreSelector.java:114)
	at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:189)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:75)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:174)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.DSpot.amplifyAllTests(DSpot.java:126)
	at fr.inria.stamp.Main.amplifyAll(Main.java:105)
	... 2 more
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:124)
	... 18 more
```

**Comment by danglotb** [comment]
It happens when **DSpot** run pit (to compute the original mutation score) the first time.

Could you please, use the `--verbose` flag to see what happens?

Thank you.

**Comment by slauriere** [comment]
Right but I'm not sure where I should add the ```--verbose``` flag, it's already in the dspot command line actually:

```
java -jar ../dspot/target/dspot-1.0.0-jar-with-dependencies.jar --verbose --path-to-properties dspot.properties --timeOut 50000
```

**Comment by danglotb** [comment]
I see that this project is multi-module.

In order to have all dependencies and co, I suggest you to modify you property file as follow:

```java
project=../imixs-workflow
targetModule=imixs-workflow-core
```

if the property file is located in the root folder of the project, _i.e._ `imixs-workflow`. In this way, **DSpot** can use values inside the `pom` of the parent.

> Right but I'm not sure where I should add the --verbose flag, it's already in the dspot command line actually:

Okay, I didn't know. Could you provide error message produce by maven just above the stacktrace that you posted?

Thank you and sorry.

**Comment by slauriere** [comment]
Many thanks. I will modify the property file accordingly.

Here's the error message by Maven:

```
5:10:27 PM PIT >> SEVERE : Description [testClass=org.imixs.workflow.xml.TestXMLItemCollectionAdapter, name=testDateValue(org.imixs.workflow.xml.TestXMLItemCollectionAdapter)] did not pass without mutation.
5:10:27 PM PIT >> INFO : MINION : 5:10:27 PM PIT >> SEVERE : Description [testClass=org.imixs.workflow.xml.TestXMLItemCollectionAdapter, name=testXMLGregrianCalendar(org.imixs.workflow.xml.TestXMLItemCollectionAdapter)]
java.lang.AssertionError: expected:<1512749422> but was:<1512749427>
	
5:10:27 PM PIT >> INFO : MINION : at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.failNotEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:126)
	at org.junit.Assert.assertEquals(Assert.java:470)
	at org.junit.Assert.assertEquals(Assert.java:454)
	at org.im
5:10:27 PM PIT >> INFO : MINION : ixs.workflow.xml.TestXMLItemCollectionAdapter.testXMLGregrianCalendar(TestXMLItemCollectionAdapter.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	
5:10:27 PM PIT >> INFO : MINION : at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.ru
5:10:27 PM PIT >> INFO : MINION : nners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.intern
5:10:27 PM PIT >> INFO : MINION : al.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

5:10:27 PM PIT >> SEVERE : Description [testClass=org.imixs.workflow.xml.TestXMLItemCollectionAdapter, name=testXMLGregrianCalendar(org.imixs.workflow.xml.TestXMLItemCollectionAdapter)] did not pass without mutation.
5:10:27 PM PIT >> INFO : Calculated coverage in 1 seconds.
|[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.134 s
[INFO] Finished at: 2017-12-08T17:10:27+01:00
[INFO] Final Memory: 13M/251M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.4:mutationCoverage (default-cli) on project imixs-workflow-core: Execution default-cli of goal org.pitest:pitest-maven:1.2.4:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.stamp.Main.amplifyAll(Main.java:107)
	at fr.inria.stamp.Main.run(Main.java:56)
	at fr.inria.stamp.Main.main(Main.java:32)
```

**Comment by danglotb** [comment]
It seems that this test are using `java.util.Date` and `java.util.GregorianCalendar`.

I think it is not a good idea to try to run **Pit** (which is run by **DSpot**) on such test.

I suggest you to exclude them using the `excludedClasses` property.
Add to your property file the following line:
`excludedClasses=org.imixs.workflow.xml.TestXMLItemCollectionAdapter`

**Comment by slauriere** [comment]
Thank you, it worked!

**Comment by danglotb** [comment]
Hi @slauriere 

I'm glad! 

Could please share result? at least the final report? It has been conclusive or not?

Thank you again!

**Comment by slauriere** [comment]
Thanks @danglotb. Actually I'm not sure how to interpret the results and how to to share the report. I get a bunch of files "xxx_mutants_killed.json" and "xxx_mutants_report.txt" but no unified report. What can I share to be helpful?

**Comment by danglotb** [comment]
Okay, It is a little bit confusing.

For each test class, you will obtain to result file.
1. is a little txt file, which contains a report of the whole ampification process on the test class
2. is a json file, with more details about each amplfied test case

I suggest that we pick up, at random one test class or maybe pick up one class for which the amplification seems to works well: _i.e._, it increases the mutation score significantly.

To do this, you can browse each of the .txt file. Inside each of them, you will find something like this:

```txt
======= REPORT =======
PitMutantScoreSelector: 
The original test suite kills XXX mutants
The amplification results with YYY new tests
it kills ZZZ more mutants
```

Where: 
* `XXX` is the absolute number of mutant killed by the original test suite (before amplification)
* `YYY` is the number of amplified test cases that increase the mutation score
* `ZZZ` is the number of (unique) mutants killed by amplified test cases

We can compute `XXX` + `ZZZ` to have the absolute number of mutant killed by the amplified test suite, _I.e._ the original test suite (before amplification) plus the obtained amplified test cases.

If you find one of them interressting, for instance that increase _a lot_ the mutation score, I suggest to post it.

You can also build a [git gist](https://gist.github.com/) with the json file and the amplified test class (which should in the same folder, but under it hierarchy of packages).

Thank you @slauriere

**Comment by slauriere** [comment]
OK @danglotb thanks, I spotted only one report that increases the mutation score and I posted it there together with the amplified test class: https://gist.github.com/slauriere/17a6469f3949b0a6bd0b26754043a2b8

**Comment by slauriere** [comment]
PS: how come there's a difference between the number of new tests in the reports (e.g. a total of 2 in the imixs-workflow-core case) and the number of amplified test classes present under the package hierarchy (e.g. a total of 29 in the same case)?

**Comment by danglotb** [comment]
AFAIU, the question is:

> Why the number of amplified tests is so small while we have a much more test classes?

The answer is because **DSpot** has not been able to produce test that increase the mutation score. In fact, it will keep only test that increase this test criterion.

In the other hand, according to the command line you provide, **DSpot** uses only A-amplification, _i.e._ generation of assertions.

In order to use I-Amplification, which will generate new test by changing the input, you may be able to kill more mutants, and produce more amplified test.

I let you try to add the following options to your command line:

`--amplifiers TestDataMutator:StatementAdd`

I suggest you to use the last release of **DSpot**. It will produce much clearer test class : find it [here](https://github.com/STAMP-project/dspot/releases/download/1.0.2/dspot-1.0.2-jar-with-dependencies.jar).

**Comment by slauriere** [comment]
Thank you @danglotb. I added the I-Amplification options to the command line and I upgraded to the latest DSpot. When running DSpot on the project, I get the following exception, while the class XMLItem is present in the source path:

```
> org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF
>> Generated 464 Killed 12 (3%)
> KILLED 12 SURVIVED 37 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 415 
--------------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.776 s
[INFO] Finished at: 2017-12-11T16:39:13+01:00
[INFO] Final Memory: 17M/504M
[INFO] ------------------------------------------------------------------------
2017-12-11 16:39:13,902 INFO fr.inria.diversify.dspot.selector.PitMutantScoreSelector - 5282 mutants has been generated (5282)
2017-12-11 16:39:13,903 INFO fr.inria.diversify.dspot.selector.PitMutantScoreSelector - testCopyValuesWithEmbeddedCollection_literalMutationString163604_failAssert0_sd164651 kills 1 more mutants
2017-12-11 16:39:13,903 INFO fr.inria.diversify.dspot.Amplification - iteration 2:
2017-12-11 16:39:13,903 INFO fr.inria.diversify.dspot.Amplification - 122 tests selected to be amplified over 122 available tests
2017-12-11 16:39:13,903 INFO fr.inria.diversify.dspot.Amplification - Amplification of inputs...
 43% |===================== ]/Exception in thread "main" java.lang.RuntimeException: spoon.support.SpoonClassNotFoundException: cannot load class: org.imixs.workflow.xml.XMLItem
	at fr.inria.stamp.Main.amplifyAll(Main.java:113)
	at fr.inria.stamp.Main.run(Main.java:62)
	at fr.inria.stamp.Main.main(Main.java:38)
Caused by: spoon.support.SpoonClassNotFoundException: cannot load class: org.imixs.workflow.xml.XMLItem
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:162)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:146)
	at spoon.support.reflect.reference.CtArrayTypeReferenceImpl.getActualClass(CtArrayTypeReferenceImpl.java:86)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getTypeDeclaration(CtTypeReferenceImpl.java:188)
	at fr.inria.diversify.dspot.amplifier.StatementAdd.findMethodsWithTargetType(StatementAdd.java:182)
	at fr.inria.diversify.dspot.amplifier.StatementAdd.lambda$useReturnValuesOfExistingMethodCall$5(StatementAdd.java:73)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at fr.inria.diversify.dspot.amplifier.StatementAdd.useReturnValuesOfExistingMethodCall(StatementAdd.java:72)
	at fr.inria.diversify.dspot.amplifier.StatementAdd.apply(StatementAdd.java:43)
	at fr.inria.diversify.dspot.Amplification.lambda$amplifyTest$6(Amplification.java:211)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.Amplification.amplifyTest(Amplification.java:217)
	at fr.inria.diversify.dspot.Amplification.lambda$amplifyTests$4(Amplification.java:201)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.Amplification.amplifyTests(Amplification.java:204)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:116)
	at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:87)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:187)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:169)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.DSpot.amplifyAllTests(DSpot.java:129)
	at fr.inria.stamp.Main.amplifyAll(Main.java:111)
	... 2 more
Caused by: java.lang.ClassNotFoundException: org.imixs.workflow.xml.XMLItem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:160)
	... 51 more
```

**Comment by danglotb** [comment]
Hi @slauriere 

Could you please retry with the latest version of **DSpot**, with taking care to include in  `additionnalClasspathElements` property generate folders.

Cheers.
