### ISSUE TITLE
Error copying some resource file

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#268]
```
2017-12-11 12:09:50,303 INFO fr.inria.diversify.utils.DSpotUtils - copy ../../xwiki-commons-core/xwiki-commons-xml/src/main/resources/xhtml-symbol.ent to ../../xwiki-commons-core/xwiki-commons-xml/target/classes/xhtml-symbol.ent
Exception in thread "main" java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at fr.inria.diversify.utils.DSpotUtils.copyFile(DSpotUtils.java:230)
	at fr.inria.diversify.utils.DSpotUtils.lambda$copyGivenResources$10(DSpotUtils.java:244)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at fr.inria.diversify.utils.DSpotUtils.copyGivenResources(DSpotUtils.java:238)
	at fr.inria.diversify.utils.DSpotUtils.copyResources(DSpotUtils.java:256)
	at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:65)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:88)
	at fr.inria.stamp.Main.run(Main.java:55)
	at fr.inria.stamp.Main.main(Main.java:38)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at fr.inria.diversify.utils.DSpotUtils.copyFile(DSpotUtils.java:217)
	... 9 more
```

When executed on commons-xml with:

```
srcResources=src/main/resources/
testResources=src/test/resources/
```

**Comment by danglotb** [comment]
This has been fixed with fecab4dca49d6fef33f8eb20c46b4c726b03ce09.
