### ISSUE TITLE
Failure to execute DSpot on SeedStack

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#282]
Steps to reproduce:

```
git clone https://github.com/seedstack/seed.git
```

dspot.properties:
```
#relative path to the project root from dspot project
project=../seed
targetModule=core
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#srcResources=src/main/resources/
#testResources=src/test/testfiles/:src/test/java/
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.seedstack.seed*
```

Output exception:

```
Exception in thread "main" spoon.compiler.ModelBuildingException: Type mismatch: cannot convert from Class<capture#2-of ? extends ErrorCode> to Class<ErrorCode> at /home/slauriere/OW2/Collabs/STAMP/code/seed/core/src/main/java/org/seedstack/seed/core/internal/diagnostic/tool/ErrorsTool.java:50
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:581)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:562)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:709)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:127)
	at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:60)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:88)
	at fr.inria.stamp.Main.run(Main.java:55)
	at fr.inria.stamp.Main.main(Main.java:38)
```

**Comment by monperrus** [comment]
duplicate of #182?

if yes, I propose to add a comment on #182 ("still failing today") rather than opening a new issue.

WDYT?

**Comment by slauriere** [comment]
thanks, sorry for the duplicate, closing this issue
