### ISSUE TITLE
DSpot build with Maven: tests are not passed

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#305]
**Issue Type**: Bug
**Description**: When building DSpot with Maven, tests are not passed. I think tests should be passed before building, as an expected good practice, particularly in the context of STAMP project, but also because, as tests are not passed and when using DSpot with DHell we are facing problems (that I  will report in another ticket) the existence of these test errors won't help to discard a bad usage when we use DSpot.
DSpot was working with DHell (as described in DSpot tutorial for Dummies) in previous versions, so I guess this could be caused by potential regression bugs.
**Reproducibility**: always 
**Severity**: major 
**Tool**: Descartes PITest, version 26/01/18
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
```
#Clone Dspot
git clone 
cd dspot/dspot
mvn package
```
Test failure:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NoClassDefFoundError: descartes/target/test-classes/fr/inria/stamp/mutationtest/test/TestCalculator (wrong name: fr/inria/stamp/mutationtest/test/TestCalculator)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
	... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

```
**Files**:
**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

I think the problem come from some state, created by previous run.

Could you try to run a `clean`? `mvn clean package`.

Also, I suggest you to take the latest release, instead of re-building **DSpot** from sources.

Thank you!

-- Benjamin.

**Comment by danzone** [comment]
Hi @jesus-gorronogoitia , I have test errors too when I execute mvn clean package from root project. But in my case it seems some corporate proxy issues are in place, because for some tests it fails to download gradle distribution. I've checked test execution results in my Travis CI account (https://travis-ci.org/danzone/dspot). It's configured to run automatically a build whenever it detects a change in my dspot forked repo: last run was yesterday evening, after a rebase with STAMP master, and no errors were detected: compilation ran fine, and all tests passed. I will investigate further on proxy issues.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin
What do you mean by?:

> Also, I suggest you to take the latest release, instead of re-building DSpot from sources.

Do you want us (UC testers) to use always latest DSpot stable versions downloadable from: 

> https://github.com/STAMP-project/dspot/releases/download/v1.0.5/dspot-1.0.5-jar-with-dependencies.jar

instead of pulling and compiling the sources?
This is fine with me.

**Comment by danglotb** [comment]
Yes exactly, you will save time.

**Comment by jesus-gorronogoitia** [comment]
Well, for me the main reason to use DSpot release is to test stable versions and not development snapshots. I think it makes more sense for you to get feedback from us on stable version only. So, I will instruct WP5 UC testers to do so.
BTW, a clean Maven build pass the tests. It was a bit presumptuous from my side to think DSpot would not pass the test because reasons on your side, I apologize.
