### ISSUE TITLE
DSpot throws exception: java.io.FileNotFoundException: ./target/dspot/classpath (No such file or directory)

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#418]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**:  block
- **Tool/Service/Component**: DSpot, version 1.1.0
- **Execution Environment**: Linux CentOS 7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot v1.1.0 triggers following exception when tested in Atos Supersede UC but also similar exceptions are thrown when executing DSpot tests or example

> Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: ./target/dspot/classpath (No such file or directory)
>     at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:77)
>     at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:33)
>     at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:27)
>     at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:91)
>     at fr.inria.stamp.Main.run(Main.java:58)
>     at fr.inria.stamp.Main.run(Main.java:88)
>     at fr.inria.stamp.Main.main(Main.java:41)
> Caused by: java.io.FileNotFoundException: ./target/dspot/classpath (No such file or directory)
>     at java.io.FileInputStream.open0(Native Method)
>     at java.io.FileInputStream.open(FileInputStream.java:195)
>     at java.io.FileInputStream.<init>(FileInputStream.java:138)
>     at java.io.FileReader.<init>(FileReader.java:72)
>     at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:74)
>  

#### Steps to reproduce
I am facing similar issues when just running tests on DSpot version 1.1.0 or just executing the DSpot example:

Running tests, I get these failures:

> Results :
> 
> Failed tests:   testSelector(fr.inria.diversify.dspot.selector.CloverCoverageSelectorTest)
>   testNoInstrumentationOnGeneratedObject(fr.inria.diversify.dspot.assertGenerator.AssertGeneratorHelperTest): expected:<..."test_sd6__1");(..)
> 
> Tests in error:
>   testPitDescartesMode(fr.inria.diversify.dspot.selector.PitScoreMutantSelectorDescartesTest): java.io.FileNotFoundException: src/test/resources/test-projects/target/dspot/classpath (No such file or directory)
> 
> Tests run: 121, Failures: 2, Errors: 1, Skipped: 3

Running the example, 
`java -jar target/dspot-1.1.0-jar-with-dependencies.jar --example`

I get:

> Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/test-projects/target/dspot/classpath (No such file or directory)
>     at fr.inria.stamp.Main.runExample(Main.java:113)
>     at fr.inria.stamp.Main.main(Main.java:39)
> Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/test-projects/target/dspot/classpath (No such file or directory)
>     at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:77)
>     at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:33)
>     at fr.inria.diversify.utils.Initializer.initialize(Initializer.java:27)
>     at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:91)
>     at fr.inria.stamp.Main.runExample(Main.java:109)
>     ... 1 more
> Caused by: java.io.FileNotFoundException: src/test/resources/test-projects/target/dspot/classpath (No such file or directory)
>     at java.io.FileInputStream.open0(Native Method)
>     at java.io.FileInputStream.open(FileInputStream.java:195)
>     at java.io.FileInputStream.<init>(FileInputStream.java:138)
>     at java.io.FileReader.<init>(FileReader.java:72)
>     at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:74)
>     ... 5 more

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, 
I think this is the problem:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project example: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
```
JAVA_HOME is defined, but probably is not pointed to a JDK. I will fix it and try again.
Concerning Maven, we are using this one: Apache Maven 3.3.9
is the any recommendation for Maven version?

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin
DSpot example works well with JDK. I will try Atos Supersede UC again before closing this issue. Merci.
Yosu

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, 
DSpot works well now that I am using JDK. Nonetheless, let me raise two issues, one associated, another not:
1- DSpot documentation does not inform (as requisite) that DSpot requires a JAVA_HOME environment variable pointing at a JDK installation (it mentions about MAVEN_HOME)
2- When DSpot is run so that mutually inconsistent target tests for amplification are specified in command line flag (-t) or dspot.properties filter, it stops mentioning that amplification failed without any further explanation (despite --verbose was activated). For instance this configuration causes DSpot to stop amplifying without a proper explanation:
```
command line flag: -t eu.supersede.integration.api.adaptation.dashboard.proxies.test.*
dspot.properties: filter=eu.supersede.integration.api.analysis.proxies.test.*
```

Another question: if I want to restrict the amplification to a list of test cases (test classes) in dspot.properties, using filter, how should I separate the different classes? using colon? For instance, is this valid?

`filter=eu.supersede.integration.api.adaptation.dashboard.proxies.test.*:eu.supersede.integration.api.analysis.proxies.test.*`

Merci

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

The property `filter` is only used by **PIT** to limit the scope of the mutation, it is not the same usage than the command line option `-t`.

With ` filter=eu.supersede.integration.api.analysis.proxies.test.*`, **PIT** will only introduce mutant inside the package `eu.supersede.integration.api.analysis.proxies.test`.

According to the name, I would say that this package contains only test, in a sense of Unit test, with assertions. I think **PIT** does not introduce mutation inside tests. This could explain why **DSpot** stops.

I would say that conventionally, the comma separate multiple values inside properties, _c.f._ [this](https://commons.apache.org/proper/commons-configuration/userguide/howto_properties.html).

> DSpot documentation does not inform (as requisite) that DSpot requires a JAVA_HOME environment variable pointing at a JDK installation (it mentions about MAVEN_HOME)

I'm gonna improve the documentation. Thank you.

**Comment by jesus-gorronogoitia** [comment]
Ok, so if I want to restrict the amplification to concrete tests, I have to use the execution flag -t and not the filter property.

**Comment by jesus-gorronogoitia** [comment]
BTW, IF code is available here (branch descartes) if you want to have a look:
[Supersede IF](https://github.com/supersede-project/integration/tree/descartes/IF/API/eu.supersede.if.api)

**Comment by danglotb** [comment]
Did you update to the lastest version of **DSpot** by pulling and rebuilding the project?

With #416 , I fixed the regression highlight by @fermenreq, _i.e._ the usage of the  `*` in the command line option `-t`.

I indeed remove the two last commit (the version before the fix) and I have the same behavior: 

```
[13837] INFO Main - Amplification failed.
[13837] INFO Main - Elapsed time 2321 ms
```

But with the fix, the amplification seems to run well (on my side).

Could you please, try to update your **DSpot**?

Thank you.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, 
Merci. I was using version 1.1.0, not the latest one, as I intended to test the latest stable version. I will use the latest version and try again.

**Comment by jesus-gorronogoitia** [comment]
I am getting an strange exception that breaks DSpot:

> Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: eu.supersede.integration.api.adaptation.dashboad.types.Enactment
> 	at fr.inria.diversify.compare.ObjectLog.load(ObjectLog.java:193)
> 

but this class does exist in classpath (or target/classes)!

Is there any way to check the classpath that it is used by DSpot?

**Comment by danglotb** [comment]
The class `fr.inria.diversify.compare.ObjectLog` is a part of the instrumentation done by **DSpot**, to observe the current program under amplification.

This error occurs when **DSpot** executes instrumented tests.

You can see the classpath on the logs:

```
2018-05-10 09:23:32,898 INFO fr.inria.diversify.dspot.assertGenerator.MethodsAssertGenerator - Run instrumented tests. (66)
2018-05-10 09:23:33,160 INFO eu.stamp.project.testrunner.EntryPoint - Run: java -cp <classpath>
```

<classpath> is the classpath used by **DSpot** to run the test, which can be huge.

 In this classpath, there are the classes of your program and some classes used by **DSpot** to run the test, collect result of their executions and classes to observe values, such as `fr.inria.diversify.compare.ObjectLog`.

I'am trying to reproduce the error, but it seems that the classpath is wrong because it does not find one of your class, _i.e._ `eu.supersede.integration.api.adaptation.dashboad.types.Enactment`.

**Comment by jesus-gorronogoitia** [comment]
There should be a bug here, because `mvn package` works well,` mvn test -Dtest=eu.supersede.integration.api.adaptation.dashboard.proxies.test.AdaptationDashboardProxyTest.java` also works well

That's why I asked how to verify the classpath used by DSpot.

**Comment by fermenreq** [comment]
Hi @jesus-gorronogoitia. @danglotb 

Once updated DSpot version: 

```
[stamp@supersede target]$ ls
archive-tmp  classes  dspot-1.1.1-SNAPSHOT.jar  dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar  generated-sources  generated-test-sources  maven-archiver  maven-status  test-classes

```
## Command line
```
java -jar target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p ../../CityGo/fiware-cygnus/cygnus-common/dspot.properties -i 3 -t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector --verbose
```

## Output
```
t.testrunner.runner.coverage.JacocoRunner /home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/classes:/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/test-classes com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:88)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:114)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.instrumentAll(JacocoRunner.java:178)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.<init>(JacocoRunner.java:80)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.main(JacocoRunner.java:45)
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:23)
        at eu.stamp.project.testrunner.runner.coverage.Coverage.load(Coverage.java:99)
        at eu.stamp.project.testrunner.EntryPoint.runCoverage(EntryPoint.java:255)
        at eu.stamp.project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:157)
        at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:59)
        at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:232)
        at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:97)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:183)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:165)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:161)
        at fr.inria.diversify.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:136)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyAllTestsNames(DSpot.java:137)
        at fr.inria.stamp.Main.run(Main.java:78)
        at fr.inria.stamp.Main.run(Main.java:92)
        at fr.inria.stamp.Main.main(Main.java:41)
Caused by: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:16)
        ... 31 more

```
Still doesnt work using an especific test and  neigther using a test suit 
It seems DSpot need **target/dspot/globalCoverageResult.ser** file

Using ``` mvn test ``` works well
```
[stamp@supersede cygnus-common]$ mvn test
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.telefonica.iot:cygnus-common:jar:1.8.0_SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.ow2.asm:asm:jar -> duplicate declaration of version 5.2 @ line 27, column 14
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 204, column 36
[WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 8, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------< com.telefonica.iot:cygnus-common >------------------
[INFO] Building cygnus-common 1.8.0_SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cygnus-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ cygnus-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cygnus-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ cygnus-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ cygnus-common ---
[INFO] Surefire report directory: /home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
 . . . .

Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec

Results :

Tests run: 105, Failures: 0, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.722 s
[INFO] Finished at: 2018-05-10T09:53:13+02:00
[INFO] ------------------------------------------------------------------------
[stamp@supersede cygnus-common]$

```


Best, 

Fernando

**Comment by jesus-gorronogoitia** [comment]
Guys, let's use different tickets for different issues. I will close this and create other tickets for the new issues I am facing. Please, Fernando, so the same for your issues, thanks.
