### ISSUE TITLE
[BUG] DSpot dont amplified Test suit, neigther individual test

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/dspot#424]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [crash, block]
- **Tool/Service/Component**: 
```
[stamp@supersede target]$ ls
archive-tmp  classes  dspot-1.1.1-SNAPSHOT.jar  dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar  generated-sources  generated-test-sources  maven-archiver  maven-status  test-classes

```
- **Execution Environment**:  Linux x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Reporter**: fernando.mendez@atos.net - fernando.mendez@atos.net

#### Description
I would like to amplifed several test from a Fiware GE component but DSpot break. The error is the same if you used my.test.package.* or using individual test

## Output
```
t.testrunner.runner.coverage.JacocoRunner /home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/classes:/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/test-classes com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:88)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:114)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.instrumentAll(JacocoRunner.java:178)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.<init>(JacocoRunner.java:80)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.main(JacocoRunner.java:45)
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:23)
        at eu.stamp.project.testrunner.runner.coverage.Coverage.load(Coverage.java:99)
        at eu.stamp.project.testrunner.EntryPoint.runCoverage(EntryPoint.java:255)
        at eu.stamp.project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:157)
        at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:59)
        at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:232)
        at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:97)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:183)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:165)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:161)
        at fr.inria.diversify.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:136)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyAllTestsNames(DSpot.java:137)
        at fr.inria.stamp.Main.run(Main.java:78)
        at fr.inria.stamp.Main.run(Main.java:92)
        at fr.inria.stamp.Main.main(Main.java:41)
Caused by: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:16)
        ... 31 more

```

It seems DSpot need **target/dspot/globalCoverageResult.ser** file

Using ``` mvn test ``` works well
```
[stamp@supersede cygnus-common]$ mvn test
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.telefonica.iot:cygnus-common:jar:1.8.0_SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.ow2.asm:asm:jar -> duplicate declaration of version 5.2 @ line 27, column 14
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 204, column 36
[WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ line 8, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------< com.telefonica.iot:cygnus-common >------------------
[INFO] Building cygnus-common 1.8.0_SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cygnus-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ cygnus-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cygnus-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ cygnus-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ cygnus-common ---
[INFO] Surefire report directory: /home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
 . . . .

Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec

Results :

Tests run: 105, Failures: 0, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.722 s
[INFO] Finished at: 2018-05-10T09:53:13+02:00
[INFO] ------------------------------------------------------------------------
[stamp@supersede cygnus-common]$

```

## Java Version

```
[stamp@supersede cygnus-common]$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Server VM (build 25.171-b11, mixed mode)
```

```
java -jar target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p ../../CityGo/fiware-cygnus/cygnus-common/dspot.properties -i 3 -t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector --verbose
```

#### Other files and URLs
https://github.com/telefonicaid/fiware-cygnus

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @fermenreq 

The root cause is:

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class org.jacoco.core.internal.flow.ClassProbesVisitor has interface org.objectweb.asm.ClassVisitor as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.<init>(JacocoRunner.java:78)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.main(JacocoRunner.java:45)
```
I am looking for a solution.

**Comment by danglotb** [comment]
A work around is to exclude `asm` from your dependencies as follow:

```
<!-- Required by HDFSBackendImplBinary -->
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-core</artifactId>
            <version>1.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

```
 <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>0.13.1</version>
            <exclusions>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm-commons</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm-tree</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I am sorry, for now, I don't have a "good" solution.

**Comment by fermenreq** [comment]
## New Changes

Dear @danglotb,
I was checking all the tests and I did the annotation ```@Ignore```  you comment before in the following tests: 

**Test: PostgreSQLCacheTest.java**
```/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/src/test/java/com/telefonica/iot/cygnus/backends/postgresql```


**Test: ManagementInterfaceTest.java**
```/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/src/test/java/com/telefonica/iot/cygnus/management```


**Test CygnusMetricsTest.java**
```/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/src/test/java/com/telefonica/iot/cygnus/metrics```


**Test KeyStoneUtilsTest.java**
```/home/stamp/Git/CityGo/fiware-cygnus/cygnus-common/src/test/java/com/telefonica/iot/cygnus/utils/auth/keystone```

## Output:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:88)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:114)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.instrumentAll(JacocoRunner.java:178)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.<init>(JacocoRunner.java:80)
        at eu.stamp.project.testrunner.runner.coverage.JacocoRunner.main(JacocoRunner.java:45)
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:23)
        at eu.stamp.project.testrunner.runner.coverage.Coverage.load(Coverage.java:99)
        at eu.stamp.project.testrunner.EntryPoint.runCoverage(EntryPoint.java:255)
        at eu.stamp.project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:157)
        at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:59)
        at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:232)
        at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:97)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:183)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:165)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:161)
        at fr.inria.diversify.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:136)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyAllTestsNames(DSpot.java:137)
        at fr.inria.stamp.Main.run(Main.java:78)
        at fr.inria.stamp.Main.run(Main.java:92)
        at fr.inria.stamp.Main.main(Main.java:41)
Caused by: java.io.FileNotFoundException: target/dspot/globalCoverageResult.ser (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:16)
        ... 31 more
```

The execution for the test was using 2 ways: one by one and all togethers test suite

```
java -jar dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p ../../CityGo/fiware-cygnus/cygnus-common/dspot.properties -i 3
-t com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest -a MethodAdd -s JacocoCoverageSelector --verbose
```
```
java -jar dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p ../../CityGo/fiware-cygnus/cygnus-common/dspot.properties -i 3
-t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector --verbose
```

Best,
Fernando Méndez

**Comment by jesus-gorronogoitia** [comment]
Done, Fernando, please, try it again
