### ISSUE TITLE
CloverCoverageSelector: Amplification failed

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#455]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot v1.1.1 latest from GitHub, built from sources
- **Execution Environment**: Linux Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot executed over DHell test project fails when used with Clover selector. Same configuration works well with Jacoco selector.

#### Steps to reproduce
Dspot built from sources. In Dhell folder, in CMI, execute the command:
`java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p /home/yosu/Projects/STAMP/Git/dhell/DSpot_Conf1_dspot.properties  -a MethodAdd -s CloverCoverageSelector -t eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest --max-test-amplified 200 -i 1 --verbose`

##### Properties file

```project=/home/yosu/Projects/STAMP/Git/dhell
src=src/main/java
testSrc=src/test/java
javaVersion=8
outputDirectory=/home/yosu/Projects/STAMP/Git/dhell/dspot-out/
filter=
```

##### Command Line / Options

```shell
java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p /home/yosu/Projects/STAMP/Git/dhell/DSpot_Conf1_dspot.properties  -a MethodAdd -s CloverCoverageSelector -t eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest --max-test-amplified 200 -i 1 --verbose
```

#### Other files and URLs
Exception:
```Exception in thread "main" java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:218)
	at eu.stamp_project.testrunner.runner.coverage.JacocoRunner.lambda$run$0(JacocoRunner.java:143)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at eu.stamp_project.testrunner.runner.coverage.JacocoRunner.run(JacocoRunner.java:138)
	at eu.stamp_project.testrunner.runner.coverage.JacocoRunner.main(JacocoRunner.java:48)
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/yosu/Projects/STAMP/Git/dhell/target/dspot/globalCoverageResult.ser does not exist.
	at eu.stamp_project.testrunner.runner.test.Loader.load(Loader.java:23)
	at eu.stamp_project.testrunner.runner.coverage.Coverage.load(Coverage.java:99)
	at eu.stamp_project.testrunner.EntryPoint.runCoverage(EntryPoint.java:263)
	at eu.stamp_project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:165)
	at eu.stamp_project.dspot.selector.CloverCoverageSelector.selectToAmplify(CloverCoverageSelector.java:69)
	at eu.stamp_project.dspot.Amplification.preAmplification(Amplification.java:203)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:91)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:174)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:156)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:152)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:127)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyAllTestsNames(DSpot.java:128)
	at eu.stamp_project.Main.run(Main.java:77)
	at eu.stamp_project.Main.run(Main.java:91)
	at eu.stamp_project.Main.main(Main.java:42)
Caused by: java.io.FileNotFoundException: /home/yosu/Projects/STAMP/Git/dhell/target/dspot/globalCoverageResult.ser does not exist.
	... 32 more

```

See dspot_execution.log file attached for the complete execution logs.
[dspot_execution.log](https://github.com/STAMP-project/dspot/files/2072762/dspot_execution.log)

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
See my answer in #456, It might be the same problem.

**Comment by jesus-gorronogoitia** [comment]
Following #456 makes the exception disappear. However, execution is tagged as successful but DSpot notifies that _Amplification failed_

> yosu@avalon:~/Projects/STAMP/Git/dhell> java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p /home/yosu/Projects/STAMP/Git/dhell/DSpot_Conf1_dspot.properties -a MethodAdd -s CloverCoverageSelector -t eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest --max-test-amplified 200 -i 1 --verbose
> 2018-06-06 10:07:15,740 WARN eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - No automatic builder specified in configuration, going to default.
> 2018-06-06 10:07:15,740 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Default: provided Maven automatic builder.
> 2018-06-06 10:07:15,754 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - run maven dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
> [WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
> [INFO] Scanning for projects...
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building hello_app 1.2.1
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ hello_app ---
> [INFO] Wrote classpath file '/home/yosu/Projects/STAMP/Git/dhell/target/dspot/classpath'.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.201 s
> [INFO] Finished at: 2018-06-06T10:07:18+02:00
> [INFO] Final Memory: 12M/240M
> [INFO] ------------------------------------------------------------------------
> 2018-06-06 10:07:18,287 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
> 2018-06-06 10:07:18,287 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - run maven clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
> [WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
> [INFO] Scanning for projects...
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building hello_app 1.2.1
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ hello_app ---
> [INFO] Deleting /home/yosu/Projects/STAMP/Git/dhell/target
> [INFO] Deleting /home/yosu/Projects/STAMP/Git/dhell (includes = [*.txt, *.traces, *.log], excludes = [])
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hello_app ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/yosu/Projects/STAMP/Git/dhell/src/main/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hello_app ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 4 source files to /home/yosu/Projects/STAMP/Git/dhell/target/classes
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hello_app ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/yosu/Projects/STAMP/Git/dhell/src/test/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hello_app ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 2 source files to /home/yosu/Projects/STAMP/Git/dhell/target/test-classes
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ hello_app ---
> [INFO] Tests are skipped.
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ hello_app ---
> [INFO] Wrote classpath file '/home/yosu/Projects/STAMP/Git/dhell/target/dspot/classpath'.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 2.666 s
> [INFO] Finished at: 2018-06-06T10:07:22+02:00
> [INFO] Final Memory: 22M/304M
> [INFO] ------------------------------------------------------------------------
> 2018-06-06 10:07:23,458 INFO eu.stamp_project.Main - Amplification failed.
> 2018-06-06 10:07:23,458 INFO eu.stamp_project.Main - Elapsed time 39 ms

**Comment by danglotb** [comment]
Hi, according to your trace, the fullqualified name of the test class that you gave is still wrong:

`eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest` should be `eu.stamp_project.examples.dhell.HelloAppTest:eu.stamp_project.examples.dhell.MyStorageTest`. 

However, I am observing another problem when computing the coverage. I'm gonna work on it.
