### ISSUE TITLE
Error injecting constructor, java.lang.NoClassDefFoundError: org/pitest/util/ServiceLoader

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#456]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot v1.1.1 latest from GitHub, built from sources
- **Execution Environment**: Linux Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot executed over DHell test project fails when used with default selector.

#### Steps to reproduce
Dspot built from sources. In Dhell folder, in CMI, execute the command:
`java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p /home/yosu/Projects/STAMP/Git/dhell/DSpot_Conf1_dspot.properties  -a MethodAdd  -t eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest --max-test-amplified 200 -i 1 --verbose`

##### Properties file

```project=/home/yosu/Projects/STAMP/Git/dhell
src=src/main/java
testSrc=src/test/java
javaVersion=8
outputDirectory=/home/yosu/Projects/STAMP/Git/dhell/dspot-out/
filter=
```
##### Command Line / Options

```shell
java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar -p /home/yosu/Projects/STAMP/Git/dhell/DSpot_Conf1_dspot.properties  -a MethodAdd  -t eu.stamp.examples.dhell.HelloAppTest:eu.stamp.examples.dhell.MyStorageTest --max-test-amplified 200 -i 1 --verbose
```
#### Other files and URLs
Exception 
```
1) Error injecting constructor, java.lang.NoClassDefFoundError: org/pitest/util/ServiceLoader
  at org.pitest.maven.PitMojo.<init>(Unknown Source)
  while locating org.pitest.maven.PitMojo

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: org/pitest/util/ServiceLoader
	at org.pitest.mutationtest.config.PluginServices.findMutationEngines(PluginServices.java:69)
	at org.pitest.mutationtest.config.PluginServices.findClientClasspathPlugins(PluginServices.java:51)
	at org.pitest.maven.DependencyFilter.<init>(DependencyFilter.java:41)
	at org.pitest.maven.AbstractPitMojo.<init>(AbstractPitMojo.java:341)
	at org.pitest.maven.PitMojo.<init>(PitMojo.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 42 more
Caused by: java.lang.ClassNotFoundException: org.pitest.util.ServiceLoader
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 63 more

```

[dspot_execution.log](https://github.com/STAMP-project/dspot/files/2072842/dspot_execution.log)

See dspot_execution.log file attached for the complete execution logs.
#### Relationships
#455 
#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia,

It seems that your properties file is not well configured.

You must have `project` property, with the path to the root of the project (where there is the `pom.xml`) for value. However, the error message does not seem to be related to this.

Thus, I strongly recommend to set a value to `filter`. The top most package with a joker would make it: `eu.stamp_project.examples.dhell*`.

I am not able to reproduce the bug.

Do you have modified your `pom.xml`, by configuring `descartes` for instance? Maybe there is something wrong such as conflict between the version of PIT used by both **descartes** and **dspot**.

You can specify a pit version to use by **dspot** by setting the property: `pitVersion`, _e.g._ `pitVersion=1.4.0`.

Something seems to be wrong. Since we deployed STAMP artifacts, we choose to change all packages to `eu.stamp_project`. According to your command line, you are using the old version of the packages.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, merci
I will follow your instructions and check what you mention. I will let you know my results.

**Comment by jesus-gorronogoitia** [comment]
It works! thanks.
Project property was included in DSpot_Conf1_dspot.properties. I just  didn't copy it well in this report.
The problem was that pom.xml was corrupted with Descartes configuration, as you suggested.
Filter seems not to have any effect. It works well with it or without it.
