### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.eclipse.emf.common.util.Uniqu eEList$FastCompare

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#562]
#### Characteristics
- **Issue Type**: bug, test report
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot latest
- **Execution Environment**: Linux Opensuse Tumbleweed

#### Description
DSpot execution on an Atos Supersede component: Model Adapter,  run with this Dspot configuration:
`-i 1 -t eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest -a MethodAdd:StatementAdd -s JacocoCoverageSelector --timeOut 30000 --verbose`
launches a runtime exception that breaks down DSpot execution :
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.eclipse.emf.common.util.Uniqu
eEList$FastCompare
        at fr.inria.diversify.compare.ObjectLog.load(ObjectLog.java:221)
        at fr.inria.diversify.compare.ObjectLog.getObservations(ObjectLog.java:193)
        at fr.inria.diversify.dspot.assertGenerator.MethodsAssertGenerator.addAssertions(MethodsAssertGenerator.java:108)
        at fr.inria.diversify.dspot.assertGenerator.AssertGenerator.innerAssertionAmplification(AssertGenerator.java:117)
        at fr.inria.diversify.dspot.assertGenerator.AssertGenerator.assertionAmplification(AssertGenerator.java:66)
        at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:140)
        at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:103)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:183)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:165)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:161)
        at fr.inria.diversify.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:136)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fr.inria.diversify.dspot.DSpot.amplifyAllTestsNames(DSpot.java:137)
        at fr.inria.stamp.Main.run(Main.java:78)
        at fr.inria.stamp.Main.run(Main.java:92)
        at fr.inria.stamp.Main.main(Main.java:41)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.eclipse.emf.common.util.UniqueEList$FastCompare
        at fr.inria.diversify.compare.ObjectLog.load(ObjectLog.java:218)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.common.util.UniqueEList$FastCompare
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:686)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1866)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1749)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2040)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1409)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2176)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at fr.inria.diversify.compare.ObjectLog.load(ObjectLog.java:216)
        ... 31 more
```
This happens after a long DSpot execution, after passing successfully the original tests (green suite), I guess during the execution of generated tests, as I saw some reporting exceptions in generated tests. But in this case, the triggered exception is a runtime one, so breaking down DSpot execution.

#### Steps to reproduce
Setting up this software component is complex, so I can perfom the checks and suggestions you may offer me.
I've checked that pom.xml contains the dependency which is apparently causing the exception:
```
<dependency>
	<groupId>org.eclipse</groupId>
	<artifactId>org.eclipse.emf.common</artifactId>
	<version>2.12.0.v20160420-0247</version>
</dependency>
```
And I've also checked that the apparently missing class: `org.eclipse.emf.common.util.Uniqu eEList$FastCompare`, is indeed located in that dependency library. 
I assume DSpot builds the classpath from Maven configuration. This configurations looks correct, and test cases are passed (greed suite).

Any idea why this dependency is not found, triggering a runtime exception that breaks DSpot when it is executing a generated test? Is there anyway to pass this dependency so it is detected in the classpath? Could it be caught, so it is not breaking DSpot execution (test could be tagged as failed)?

Please, let me know additional information I should provide you to understand this situation, and any debugging process I could do from my side, to help you, since, as I told you, setting up this component for running tests is a little bit complex.

This is really a critical situation, because, if not solved, we cannot test DSpot and compute associated KPIs.

Don't hesitate to contact me for any further information and support.

##### Properties file

```
project=./
src=src/main/java/
testSrc=src/test/java
srcResources=src/main/resources/
javaVersion=8
outputDirectory=dspot-out/
jvmArgs=['-Xmx2048m','-Xms1024m']

```

##### Command Line / Options

```shell
java -jar target/dspot-USED-VERSION-jar-with-dependencies.jar \
-p myPropertiesFile.properties
```

#### Other files and URLs
See the [log](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/JacocoCoverageSelector/MethodAdd:StatementAdd/201809281248/dspot.log) of this experiment.

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
Thanks for your hint, I will update DSpot from GitHub and test it again. 
BTW,
What is your recommendation for DSpot configuration in terms of Selectors and Amplifiers, in order to get better code coverage (and amplified tests) results?
With current configuration DSpot takes hours to complete

**Comment by danglotb** [comment]
The default configuration is `PitMutantScoreSelector`. With this selector, **DSpot** will run the mutation analysis on the whole project, using all the test classes, which can be quite long. 

Since the original mutation analysis is long, **DSpot** can take as input a CSV file that contains it. To obtain it, you can run PIT on your project and save the csv reports to a specific place, (_e.g._ at the root of the project) and then give it to **DSpot** with the following CLI: `--path-pit-result <path>`.

To run PIT, you can launch to following maven goals from the root of the project:

```shell
mvn clean test -DskipTests org.pitest:pitest-maven:1.3.0:mutationCoverage -DtargetClasses=your.top.package* -DtargetTestClasses=your.top.package* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV -Dmutators=ALL
```
Change "your.top.package*" by the value of your top package (for **DSpot** it would be `eu.stamp_project.*`.

I will take a while to complete, but after that you will have the mutation analysis report in `target/pit-reports/<date>/mutations.csv`

Just copy the `mutations.csv` (if let it in the `target` folder, it will be erase at the first `mvn clean`) and give it to **DSpot**.

For the code coverage, I would suggest you to use `CloverCoverageSelector`, _i.e._ `--test-criterion CloverCoverageSelector` which use [OpenClover](https://openclover.org/) to compute the statement coverage, and keep only amplified test methods that increase it.

Concerning the input amplification, I would suggest the following:
- `AllLiteralAmplifiers`
- `MethodGeneratorAmplifier`
- `ReturnValueAmplifier`
- `NullifierAmplifier`

_i.e._ `--amplifiers AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier` on Linux.

In any case, from my experience what it is take most of the time is the execution of tests (original and amplified). If your tests take long time to be executed (more than 5s), **DSpot** will take long time too.

You can still reduce the number of amplified test using `--max-test-amplified` (default: 200), but you will reduce the exploration and thus the potential to find "interresting" amplified test methods.

Best.

**Comment by danglotb** [comment]
These bugs persist, or we must follow on #563? If so, I would close this one.

**Comment by jesus-gorronogoitia** [comment]
I guess so, I just change the DSpot configuration following your suggestions, but I did not check it again with the configuration used in the report. I will test it again and report.
These days I am attending another project meeting, so it will take me some time to complete the tests.
