### ISSUE TITLE
DSpot: CloverCoverageSelector: Some test(s) failed during computation of coverage: java.lang.RuntimeException: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#564]
#### Characteristics
- **Issue Type**: bug, test report
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot Latest
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
When Dspot is executed with CloverCoverageSelector on Atos Supersede Model Adapter component (see #562 for details), DSpot concludes execution reporting:
```
Some test(s) failed during computation of coverage:
testModelAdapter_applyUpdateComposition_method(eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest): tried to access class eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest$1 from class eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest
```
However, running mvn test or Clover on this component using:
`mvn -f pom_clover.xml clean clover:setup test clover:aggregate clover:clover
`
works well.
Observing DSpot logs I see an exception triggered during the test execution, so I assume above report could be caused by this exception:

```
java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at eu.stamp_project.dspot.selector.CloverCoverageSelector.init(CloverCoverageSelector.java:52)
        at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:94)
        at eu.stamp_project.Main.run(Main.java:49)
        at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at eu.stamp_project.testrunner.EntryPoint.runGivenCommandLine(EntryPoint.java:356)
        at eu.stamp_project.testrunner.EntryPoint.runCoverage(EntryPoint.java:307)
        at eu.stamp_project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:211)
        at eu.stamp_project.dspot.selector.CloverCoverageSelector.init(CloverCoverageSelector.java:46)
        ... 3 more
```
Is there any way to increase the TIMEOUT when DSpot is calling Clover? When I launch Clover on the component, I don't get that exception.

#### Steps to reproduce
See #562 
##### Properties file

Same as in #562 for details

#### Other files and URLs
See execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/CloverCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810011233/nohup.out).

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

>Is there any way to increase the TIMEOUT when DSpot is calling Clover? When I launch Clover on the component, I don't get that exception.

Yes, it is the command line option: `--timeOut` but it seems that you have already increased it.

The current failure comes from JaCoCo. In fact, the `CloverCoverageSelector` is using JaCoCo to compute the global coverage of the project, in addition to the coverage per test.

Are able to run JaCoCo on the project?

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb do you mean to run DSpot with JacocoCoverageSelector? Yes, in previous Dspot runs I used Jacoco, not facing this problem. Or do you mean to run Jacoco alone to compute code coverage, as I did with Clover?

**Comment by danglotb** [comment]
I meant this:
> Or do you mean to run Jacoco alone to compute code coverage, as I did with Clover?

But if you did with the `JacocoCoverageSelector`, it is not related to JaCoCo but the usage of JaCoCo by the `CloverCoverageSelector`.

**Comment by jesus-gorronogoitia** [comment]
Anyway, I will configure Jacoco in pom.xml to compute code coverage but its own and give you more insights.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I've instrumented our component using Jacoco. I get the report without problems, using following Maven configuration:
```
 			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.2</version>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
					<execution>
						<id>post-unit-test</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<!-- Sets the path to the file which contains the execution data. -->

							<dataFile>target/jacoco.exec</dataFile>
							<!-- Sets the output directory for the code coverage report. -->
							<outputDirectory>target/jacoco-ut</outputDirectory>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<systemPropertyVariables>
						<jacoco-agent.destfile>target/jacoco.exec</jacoco-agent.destfile>
					</systemPropertyVariables>
				</configuration>
			</plugin>
```
There is only an exception triggered complaining of a long method:
```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/eclipse/uml2/uml/util/UMLSwitch.
	at org.jacoco.agent.rt.internal_28bab1d.CoverageTransformer.transform(CoverageTransformer.java:93)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.uml2.uml.util.UMLUtil.getEcoreName(UMLUtil.java:11605)
	at org.eclipse.uml2.uml.util.UMLUtil.basicGetNamedElement(UMLUtil.java:11744)
	at org.eclipse.uml2.uml.util.UMLUtil.getNamedElement(UMLUtil.java:11710)
	at org.eclipse.uml2.uml.util.UMLUtil.getStereotype(UMLUtil.java:11822)
	at org.eclipse.uml2.uml.util.UMLUtil.getStereotype(UMLUtil.java:11849)
	at org.eclipse.uml2.uml.internal.operations.ElementOperations.getAppliedStereotypes(ElementOperations.java:340)
	at org.eclipse.uml2.uml.internal.impl.ElementImpl.getAppliedStereotypes(ElementImpl.java:246)
	at org.eclipse.uml2.uml.internal.operations.ElementOperations.getAppliedStereotype(ElementOperations.java:364)
	at org.eclipse.uml2.uml.internal.impl.ElementImpl.getAppliedStereotype(ElementImpl.java:259)
	at org.eclipse.uml2.uml.internal.operations.ClassOperations.isMetaclass(ClassOperations.java:211)
	at org.eclipse.uml2.uml.internal.impl.ClassImpl.isMetaclass(ClassImpl.java:1057)
	at org.eclipse.uml2.uml.internal.operations.ClassOperations.getExtensions(ClassOperations.java:140)
	at org.eclipse.uml2.uml.internal.operations.ClassOperations.getExtensions(ClassOperations.java:123)
	at org.eclipse.uml2.uml.internal.impl.ClassImpl.getExtensions(ClassImpl.java:826)
	at org.eclipse.uml2.uml.internal.impl.ClassImpl.eIsSet(ClassImpl.java:1728)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eIsSet(BasicEObjectImpl.java:1241)
	at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:437)
	at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.next(EContentsEList.java:595)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolveCrossReferences(EcoreUtil.java:304)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:298)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:283)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:271)
	at eu.supersede.dynadapt.aom.dsl.util.SupersedeDSLResourceSet.loadModel(SupersedeDSLResourceSet.java:380)
	at eu.supersede.dynadapt.aom.dsl.util.SupersedeDSLResourceSet.loadModel(SupersedeDSLResourceSet.java:396)
	at eu.supersede.dynadapt.model.ModelManager.getUMLModel(ModelManager.java:114)
	at eu.supersede.dynadapt.model.ModelManager.loadUMLModel(ModelManager.java:98)
	at eu.supersede.dynadapt.aom.dsl.parser.AdaptationParser.loadUMLResource(AdaptationParser.java:50)
	at eu.supersede.dynadapt.modelrepository.repositoryaccess.ModelRepository.loadModel(ModelRepository.java:113)
	at eu.supersede.dynadapt.modelrepository.repositoryaccess.GenericModelRepository.getModel(GenericModelRepository.java:343)
	at eu.supersede.dynadapt.modelrepository.repositoryaccess.GenericModelRepository.getLatestModelOfTypeForSystemWithStatus(GenericModelRepository.java:423)
	at eu.supersede.dynadapt.modelrepository.repositoryaccess.ModelRepository.getLastBaseModelForSystem(ModelRepository.java:464)
	at eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest.testModelAdapter_applyUpdateComposition_method(ModelAdapterTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.io.IOException: Error while instrumenting org/eclipse/uml2/uml/util/UMLSwitch.
	at org.jacoco.agent.rt.internal_28bab1d.core.instr.Instrumenter.instrumentError(Instrumenter.java:175)
	at org.jacoco.agent.rt.internal_28bab1d.core.instr.Instrumenter.instrument(Instrumenter.java:125)
	at org.jacoco.agent.rt.internal_28bab1d.CoverageTransformer.transform(CoverageTransformer.java:91)
	... 84 more
Caused by: org.jacoco.agent.rt.internal_28bab1d.asm.MethodTooLargeException: Method too large: org/eclipse/uml2/uml/util/UMLSwitch.doSwitch (ILorg/eclipse/emf/ecore/EObject;)Ljava/lang/Object;
	at org.jacoco.agent.rt.internal_28bab1d.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2080)
	at org.jacoco.agent.rt.internal_28bab1d.asm.ClassWriter.toByteArray(ClassWriter.java:459)
	at org.jacoco.agent.rt.internal_28bab1d.core.instr.Instrumenter.instrument(Instrumenter.java:104)
	at org.jacoco.agent.rt.internal_28bab1d.core.instr.Instrumenter.instrument(Instrumenter.java:123)
	... 85 more

```
but not any timeout exception.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb I've tested DSpot with Clover selector in another Atos component, and I also get the same java.lang.RuntimeException: java.util.concurrent.TimeoutException. However, I can compute the complete Clover analysis using the Clover plugin for Maven.
I am going to try DSpot with Jacoco selector, and then with PIT one.

**Comment by jesus-gorronogoitia** [comment]
Despite this error, Dspot keeps working, so I will wait to it to complete the job.
