### ISSUE TITLE
DSpot block on Atos Supersede IF use case during instrumentation

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#570]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: DSpot latest version built from sources
- **Execution Environment**: Linux CentOS 7
- **Reporter**: Jesús Gorroñogoitia
#### Description
DSpot stop working (but it doesn't quit) during (apparently) the instrumentation phase.
Dspot was executed in Supersede IF component targeting the amplification of a single test:
`-t eu.supersede.integration.api.adaptation.dashboard.proxies.test.AdaptationDashboardProxyTest`

However, it gets blocked with the following exeception (not related with Dspot at all, but with IF test):
`java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "eu/supersede/integration/api/pubsub/test/AlertPubSubTest"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at eu.supersede.integration.api.pubsub.test.AlertPubSubTest$AlertMessageListener.onMessage(AlertPubSubTest.java:128)
        at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:747)
        at org.wso2.andes.client.BasicMessageConsumer.notifyMessage(BasicMessageConsumer.java:721)
        at org.wso2.andes.client.AMQSession$Dispatcher.notifyConsumer(AMQSession.java:3537)
        at org.wso2.andes.client.AMQSession$Dispatcher.dispatchMessage(AMQSession.java:3477)
        at org.wso2.andes.client.AMQSession$Dispatcher.access$1200(AMQSession.java:3226)
        at org.wso2.andes.client.AMQSession.dispatch(AMQSession.java:3219)
        at org.wso2.andes.client.message.UnprocessedMessage.dispatch(UnprocessedMessage.java:54)
        at org.wso2.andes.client.AMQSession$Dispatcher.run(AMQSession.java:3399)
        at java.lang.Thread.run(Thread.java:748)
`

It seems DSpot is executing test: eu.supersede.integration.api.pubsub.test.AlertPubSubTest
which is not related to the target one.
So, in order to avoid DSpot to amplify (even instrument) that test (or whatever other that is not the target one), I added the following configuration to the dspot.properties
`#excludedClasses: specify the full qualified name of excluded test classes. Each qualified name must be separated by a comma ','. These classes won't be amplified, nor executed during the mutation analysis, if the PitMutantScoreSelector is used.This property can be valued by a regex.
excludedClasses=eu.supersede.integration.api.adaptation.proxies.test*,eu.supersede.integration.api.analysis.proxies.test*,eu.supersede.integration.api.datastore.proxies.test*,eu.supersede.integration.api.dm.proxies.test*,eu.supersede.integration.api.fe.test*,eu.supersede.integration.api.feedback.proxies.test*,eu.supersede.integration.api.mdm.proxies.test*,eu.supersede.integration.api.monitoring.proxies.test*,eu.supersede.integration.api.proxies.test*,eu.supersede.integration.api.pubsub.test*,eu.supersede.integration.api.replan.controller.proxies.test*,eu.supersede.integration.api.replan.optimizer.proxies.test*,eu.supersede.integration.api.security.test*,eu.supersede.integration.api.tenants.test*,eu.supersede.integration.application*,eu.supersede.integration.federation.test*
`
But, it didn't work and I still get the same exception, which blocks me.
Any idea to avoid DSpot to do whatever action with tests that are not included in the target list?

#### Steps to reproduce
DSpot is executed in component IF with [run_dspot.sh](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier/201810151258/run_dspot.sh) script 

##### Properties file

See [dspot.properties](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier/201810151258/dspot.properties)

##### Command Line / Options

See [run_dspot.sh](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier/201810151258/run_dspot.sh)

#### Other files and URLs
See DSpot execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier/201810151258/dspot.log).

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

I'm gonna look if the exclusion works well. Keep you update.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb I've pulled Dspot code from GitHub, compiled it and tested the new DSpot with the same configuration I used when I reported this issue. I still get that all tests executed (despite they all excepting the target test class have been excluded in the dspot.properties file) and the same exception triggered:
`java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "eu/supersede/integration/api/pubsub/test/AlertPubSubTest"
`

**Comment by jesus-gorronogoitia** [comment]
Can you add a log in DSpot informing of the test classes that will be excluded, so we can check whether or not this exclusion it managed? I also wonder if my way to use wildcards for excluding test classes is correct:
`excludedClasses=eu.supersede.integration.api.adaptation.proxies.test*,eu.supersede.integration.api.analysis.proxies.test*,eu.supersede.integration.api.datastore.proxies.test*,eu.supersede.integration.api.dm.proxies.test*,eu.supersede.integration.api.fe.test*,eu.supersede.integration.api.feedback.proxies.test*,eu.supersede.integration.api.mdm.proxies.test*,eu.supersede.integration.api.monitoring.proxies.test*,eu.supersede.integration.api.proxies.test*,eu.supersede.integration.api.pubsub.test*,eu.supersede.integration.api.replan.controller.proxies.test*,eu.supersede.integration.api.replan.optimizer.proxies.test*,eu.supersede.integration.api.security.test*,eu.supersede.integration.api.tenants.test*,eu.supersede.integration.application*,eu.supersede.integration.federation.test*
`

**Comment by danglotb** [comment]
> I also wonder if my way to use wildcards for excluding test classes is correct
According to this [test](https://github.com/STAMP-project/dspot/blob/master/dspot/src/test/resources/sample/sample.properties#L8), the wildcard is working.

> Can you add a log in DSpot informing of the test classes that will be excluded, so we can check whether or not this exclusion it managed? 

Yes, I can do that. Also, I would like that you provide me the logs of the execution (after updating **DSpot**) 

Thank you.

**Comment by jesus-gorronogoitia** [comment]
See execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/CloverCoverageSelector/AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier/201810161639/dspot.log)

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

According to the [java documentation](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html) the start is not a wildcard that allow to match "anything" but it is a quantifier (zero or more times).

Your regex are built as follow: `my.package*` and so, it tries to match `my.package` zero or one times, and not as you expected `my.package<whatever.it.follows>` (I think).

In my test, I do `fr.inria.filter.failing.*`. Here, the end (`.*`) is the most important: 
- the dot `.` means any characters.
- the start `*`, as said, means zero or more times.

According to the documention and the test, the wildcard is `.*` and not only `*`.

I suggest you to modify your properties with `.*` instead of `*`.

On my side, I tried but I obtain a timeout exception. It is normal or it should not? I have an issue with the test runner.

It seems that your test is still running and the test runner is not able to kill.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb thanks for your support. I am updating DSpot by pulling its repository and building its sources,so I can try again this correct way to use * in regex. You cannot make the tests to work because the server that hosts required services is not accessible (that's the reason you get timeouts, sorry I cannot open the server to Internet because of Atos policies). So,  I will try it now and I will keep you informed.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
Now, I get the following exception:
`Error: Could not find or load main class ['-Xmx2048m'
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/stamp/Git/Supersede/integration/IF/API/eu.supersede.if.api/target/dspot/globalCoverageResult.ser does not exist.
	at eu.stamp_project.testrunner.runner.test.Loader.load(Loader.java:23)
	at eu.stamp_project.testrunner.runner.coverage.Coverage.load(Coverage.java:100)
	at eu.stamp_project.testrunner.EntryPoint.runCoverage(EntryPoint.java:312)
	at eu.stamp_project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:211)
	at eu.stamp_project.dspot.selector.CloverCoverageSelector.init(CloverCoverageSelector.java:46)
	at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:92)
	at eu.stamp_project.Main.run(Main.java:49)
	at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.io.FileNotFoundException: /home/stamp/Git/Supersede/integration/IF/API/eu.supersede.if.api/target/dspot/globalCoverageResult.ser does not exist.
`
Note that I've just pulled dspot repository, build the dspot jar and try again with an fixed dspot.properties file that places correctlly the * wildcard, exactly as your example below.
This issue with the `globalCoverageResult.ser` was reported before, as far as I remember, and that was one of the reasons I never could make Clover selector to work. Meantime I wait for your support, I will try again with Jacoco selector (which worked before for me in this component). I switched to Clover because you suggested me to do so.

**Comment by jesus-gorronogoitia** [comment]
#465

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb It was my failure, you informed me in another issue that the jvmArgs entry changed in dspot.properties. Now I've fixed it and it works well for Jacoco. I will try now for Clover.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb It also works with Clover.
I've noticed that in a simple experiment, one iteration, with Jacoco I get 32 amplified test and a 5% of coverage improvement, while for Clover I get 0 amplified tests, and therefore, 0% of coverage improvement.
What is your advice for getting optimal coverage improvement? Should I try Clover with higher iterations?

BTW, this is the DSpot CLI parameters (only selector changes):
`DSpot configuration:  -i 1 -t eu.supersede.integration.api.adaptation.dashboard.proxies.test.AdaptationDashboardProxyTest -a AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier -s CloverCoverageSelector --timeOut 30000 --verbose`

**Comment by jesus-gorronogoitia** [comment]
Increasing the number of iterations with Clover selector does not succeed in generating amplified tests. Meantime I get your advice, I will keep working with Jacoco selector.

**Comment by danglotb** [comment]
HI @jesus-gorronogoitia 

It might have an issue with the CloverSelector. But, since the CloverSelector aims at increasing the Branch coverage, while JacocoSelector aims the instructions coverage, it seems also legit that we obtain more improvement with Jacoco.

The problem with Jacoco, is that the selection of the amplified test methods (that actually increase the instruction coverage) is not accurate. In other words, DSpot can say that a bunch of amplified test methods is increasing the instruction coverage while it is not true, only a few of them are. 

From the instruction coverage increase point of view, this is not a problem since you keep the same, but you have some amplified test methods that are useless, and thus use some execution time for nothing.

Anyway, I'm gonna investigate on the usage of the CloverSelector.
