### ISSUE TITLE
Failure to run dspot with --descartes on xwiki-commons-component-default

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#584]
Built dspot from sources just now and executed the following in `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default`:

```
java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --descartes --verbose --generate-new-test-class --with-comment
```

And got:

```
...
2018-10-17 16:33:31,142 INFO eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator - Run instrumented tests. (6)
2018-10-17 16:33:31,277 INFO eu.stamp_project.testrunner.EntryPoint - Run: java  -classpath /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/test-classes:/Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/classes/:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-component-api/10.9-SNAPSHOT/xwiki-commons-component-api-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-stability/10.9-SNAPSHOT/xwiki-commons-stability-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-text/10.9-SNAPSHOT/xwiki-commons-text-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar:/Users/vmassol/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/vmassol/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-component-observation/10.9-SNAPSHOT/xwiki-commons-component-observation-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-observation-api/10.9-SNAPSHOT/xwiki-commons-observation-api-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-tool-test-simple/10.9-SNAPSHOT/xwiki-commons-tool-test-simple-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/vmassol/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.3.1/junit-jupiter-api-5.3.1.jar:/Users/vmassol/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/Users/vmassol/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-commons/1.3.1/junit-platform-commons-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.3.1/junit-jupiter-engine-5.3.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-engine/1.3.1/junit-platform-engine-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-launcher/1.3.1/junit-platform-launcher-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/vintage/junit-vintage-engine/5.3.1/junit-vintage-engine-5.3.1.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/vmassol/.m2/repository/org/jmock/jmock/2.6.0/jmock-2.6.0.jar:/Users/vmassol/.m2/repository/org/jmock/jmock-junit4/2.6.0/jmock-junit4-2.6.0.jar:/Users/vmassol/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/vmassol/.m2/repository/org/mockito/mockito-core/2.23.0/mockito-core-2.23.0.jar:/Users/vmassol/.m2/repository/net/bytebuddy/byte-buddy/1.9.0/byte-buddy-1.9.0.jar:/Users/vmassol/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.0/byte-buddy-agent-1.9.0.jar:/Users/vmassol/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/Users/vmassol/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/vmassol/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/vmassol/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/vmassol/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/Users/vmassol/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar:/Users/vmassol/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/dependencies/:/Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar eu.stamp_project.testrunner.runner.test.TestRunner org.xwiki.component.ProviderTest loadAndInjectProviderWhenExceptionInInitialize_withlog0:loadAndInjectProviders_withlog0:loadAndInjectProviderWhenExceptionInInitialize_withlog1:loadAndInjectProviders_withlog1:loadAndInjectProviderWhenExceptionInInitialize_withlog2:loadAndInjectProviders_withlog2
File saved to the following path: /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/observations.ser
File saved to the following path: /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/TestListener.ser
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/vmassol/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Loading /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/TestListener.ser
2018-10-17 16:33:31,943 INFO eu.stamp_project.testrunner.EntryPoint - Test has been run: loadAndInjectProviders_withlog0,loadAndInjectProviders_withlog1,loadAndInjectProviders_withlog2,loadAndInjectProviderWhenExceptionInInitialize_withlog0,loadAndInjectProviderWhenExceptionInInitialize_withlog1,loadAndInjectProviderWhenExceptionInInitialize_withlog2
2018-10-17 16:33:31,961 INFO eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator - Generating assertions...
2018-10-17 16:33:32,364 INFO eu.stamp_project.dspot.assertgenerator.AssertGenerator - 2 new tests with assertions generated
2018-10-17 16:33:32,478 INFO eu.stamp_project.testrunner.EntryPoint - Run: java  -classpath /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/test-classes:/Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/classes/:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-component-api/10.9-SNAPSHOT/xwiki-commons-component-api-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-stability/10.9-SNAPSHOT/xwiki-commons-stability-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-text/10.9-SNAPSHOT/xwiki-commons-text-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar:/Users/vmassol/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/vmassol/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-component-observation/10.9-SNAPSHOT/xwiki-commons-component-observation-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-observation-api/10.9-SNAPSHOT/xwiki-commons-observation-api-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-tool-test-simple/10.9-SNAPSHOT/xwiki-commons-tool-test-simple-10.9-SNAPSHOT.jar:/Users/vmassol/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/vmassol/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.3.1/junit-jupiter-api-5.3.1.jar:/Users/vmassol/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/Users/vmassol/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-commons/1.3.1/junit-platform-commons-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.3.1/junit-jupiter-engine-5.3.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-engine/1.3.1/junit-platform-engine-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/platform/junit-platform-launcher/1.3.1/junit-platform-launcher-1.3.1.jar:/Users/vmassol/.m2/repository/org/junit/vintage/junit-vintage-engine/5.3.1/junit-vintage-engine-5.3.1.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/vmassol/.m2/repository/org/jmock/jmock/2.6.0/jmock-2.6.0.jar:/Users/vmassol/.m2/repository/org/jmock/jmock-junit4/2.6.0/jmock-junit4-2.6.0.jar:/Users/vmassol/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/vmassol/.m2/repository/org/mockito/mockito-core/2.23.0/mockito-core-2.23.0.jar:/Users/vmassol/.m2/repository/net/bytebuddy/byte-buddy/1.9.0/byte-buddy-1.9.0.jar:/Users/vmassol/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.0/byte-buddy-agent-1.9.0.jar:/Users/vmassol/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/Users/vmassol/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/vmassol/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/vmassol/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/vmassol/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/Users/vmassol/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar:/Users/vmassol/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/dependencies/:/Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar eu.stamp_project.testrunner.runner.test.TestRunner org.xwiki.component.ProviderTest loadAndInjectProviderWhenExceptionInInitialize:loadAndInjectProviders
File saved to the following path: /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/TestListener.ser
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/vmassol/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Loading /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/TestListener.ser
2018-10-17 16:33:33,036 INFO eu.stamp_project.testrunner.EntryPoint - Test has been run: loadAndInjectProviderWhenExceptionInInitialize,loadAndInjectProviders(org.xwiki.component.ProviderTest): expected:<1798074022> but was:<-583453160>
2018-10-17 16:33:33,036 INFO eu.stamp_project.dspot.Amplification - Assertion amplification: 1 test method(s) has been successfully amplified.
2018-10-17 16:33:33,063 WARN spoon.Launcher - You specified the directory /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/classes in source classpath, please note that only class files will be considered. Jars and subdirectories will be ignored.
2018-10-17 16:33:33,077 WARN spoon.Launcher - You specified the directory /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/test-classes in source classpath, please note that only class files will be considered. Jars and subdirectories will be ignored.
2018-10-17 16:33:33,079 WARN spoon.Launcher - You specified the directory /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/../../../xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/target/dspot/dependencies in source classpath, please note that only class files will be considered. Jars and subdirectories will be ignored.
Exception in thread "main" org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at com.sun.org.apache.xerces.internal.dom.NodeImpl.insertBefore(NodeImpl.java:481)
	at com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:237)
	at eu.stamp_project.mutant.descartes.DescartesInjector.getNodeNamedFromOrBuildIfDoesnotExist(DescartesInjector.java:40)
	at eu.stamp_project.mutant.descartes.DescartesInjector.injectDescartesIntoPom(DescartesInjector.java:119)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.initializeForDescartes(MavenAutomaticBuilder.java:73)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:149)
	at eu.stamp_project.dspot.selector.PitMutantScoreSelector.selectToKeep(PitMutantScoreSelector.java:117)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:85)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:179)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:148)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:126)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:107)
	at eu.stamp_project.Main.run(Main.java:56)
	at eu.stamp_project.Main.main(Main.java:40)
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default (master *+) $ 
```

**Comment by vmassol** [comment]
FTR it works fine with `java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --verbose --generate-new-test-class --with-comment` so the issue is `--descartes`.

**Comment by vmassol** [comment]
@danglotb I'm a bit stuck now for measuring KPIs for STAMP. Would be great if you could look at this. Thx

**Comment by danglotb** [comment]
It should be fixed after #589 will be merged. Please if the problem persists, reopen this issue.

**Comment by vmassol** [comment]
This is definitely not working and is now causing 2 problems:
1) Dspot modifies my pom.xml ! It added 2 lines:

`<dependency><groupId>org.pitest</groupId><artifactId>pitest-maven</artifactId><version>1.4.0</version></dependency><dependency><groupId>eu.stamp-project</groupId><artifactId>descartes</artifactId><version>1.2.4</version></dependency>`

and

`<plugin><groupId>org.pitest</groupId><artifactId>pitest-maven</artifactId><version>1.4.0</version><configuration><mutationEngine>descartes</mutationEngine><mutators><mutator>void</mutator><mutator>null</mutator><mutator>true</mutator><mutator>false</mutator><mutator>empty</mutator><mutator>0</mutator><mutator>1</mutator><mutator>(byte)0</mutator><mutator>(byte)1</mutator><mutator>(short)1</mutator><mutator>(short)2</mutator><mutator>0L</mutator><mutator>1L</mutator><mutator>0.0</mutator><mutator>1.0</mutator><mutator>0.0f</mutator><mutator>1.0f</mutator><mutator>' '</mutator><mutator>'A'</mutator><mutator>""</mutator><mutator>"A"</mutator></mutators></configuration><dependencies><dependency><groupId>eu.stamp-project</groupId><artifactId>descartes</artifactId><version>1.2.4</version></dependency></dependencies></plugin>`

2) It fails with:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.271 s
[INFO] Finished at: 2018-10-18T10:06:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:mutationCoverage (default-cli) on project xwiki-commons-component-default: Execution default-cli of goal org.pitest:pitest-maven:1.4.0:mutationCoverage failed: Illegal base64 character 3c -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:228)
	at eu.stamp_project.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:66)
	at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:92)
	at eu.stamp_project.Main.run(Main.java:49)
	at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:225)
	... 4 more
```

Would be great if you could fix this and verify it works for you on `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default`. Thanks Benjamin

**Comment by danglotb** [comment]
> Dspot modifies my pom.xml ! It added 2 lines:

Do you know how to run Descartes without modifying the `pom.xml`?

> Would be great if you could fix this and verify it works for you on xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default. Thanks Benjamin

I did but I probably don't have the same state than yours.

Did you modify your `pom.xml` for instance?

**Comment by vmassol** [comment]
> Do you know how to run Descartes without modifying the pom.xml? See STAMP-project/pitest-descartes#48

What is not good is to leave the change after DSpot finishes executing. It's not great that you need to modify it during execution but at least if put it back at the end it's more acceptable.

Right now if your run Dspot and then run "mvn clean install" on this module you'll see it fails because of what Dspot changed in the pom.xml.... 

> I did but I probably don't have the same state than yours.

I've on master without any change so you must have the same as I have.

I have an idea why it could fail (but should be the same for you): if DSpot modifies the pom.xml and then executes XWiki's build it will fail since the dspot maven plugin is declared as a project dependency and is transitively drawing commons-logging which is forbidden in XWiki.

Also, I don't know why you're adding a new `<dependency>` since you add the dspot maven plugin as a plugin and thus it's not needed.

Thanks

**Comment by danglotb** [comment]
> What is not good is to leave the change after DSpot finishes executing. It's not great that you need to modify it during execution but at least if put it back at the end it's more acceptable.

Yes, I though I did, but the call to the corresponding method has been removed. #593 should fix this.

> Also, I don't know why you're adding a new <dependency> since you add the dspot maven plugin as a plugin and thus it's not needed.

Okay, I don't remember why. Anyway, #593 makes DSpot do not introduce this new dependency.

> I've on master without any change so you must have the same as I have.

I ran several time on the concerned module of xwiki, and DSpot completed its execution.

> Illegal base64 character 3c 

I already saw this errors quite often. @andrewbwogi has this error and we figure out that the `history` of PIT, that should make it faster, was responsible for PIT 1.4.0, that is why we downgraded the default version to 1.3.0. But it seems that Descartes need PIT 1.4.0 (see #560).

Anyway, I disable the history with #593. It should be fine after the merge.

**Comment by vmassol** [comment]
Thanks, I've git pulled and rebuilt dspot (with `mvn clean install -DskipTests`) and tried again and same results (pom.xml is still modified and same error with "Illegal base64 character 3c").

I'm running with `java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --descartes --verbose --generate-new-test-class --with-comment`.

**Comment by danglotb** [comment]
I just merged #593.

Please retry and keep me update of your progress.

**Comment by vmassol** [comment]
Thanks Benjamin. It doesn't fail anymore! :) However I didn't get any new test generated.... I got 2 with PIT/Gregor and 19 with Jacoco (AFAIR). Could it be that PIT/Descartes will generate less tests than PT/Gregor? Have you noticed this?

Thx

**Comment by danglotb** [comment]
> Could it be that PIT/Descartes will generate less tests than PT/Gregor? Have you noticed this?

My intuition is yes: with Descartes, DSpot will generate generate fewer amplified tests, however I do not have evidence of this.

Maybe it is because Descartes generate fewer mutants than Gregor and the extreme mutants are harder to kill, generate more equivalent mutants.

**Comment by vmassol** [comment]
@bbaudry Right now this is a problem for measuring the KPIs since K03 is about increasing the mutation score but based on Descartes. In our tests, when we used DSpot with PIT/Gregor is either led to 0% mutation increase as measured by Descartes or negative % values... So we're a bit stuck FTM and we need to decide what to do.

We have another problem, specific to XWiki: we've put in place the break of the build when the Descartes mutation score decreases, so we can't include the tests generated by DSpot if they decrease the Descartes mutation score or it would break our build...

**Comment by danglotb** [comment]
>  so we can't include the tests generated by DSpot if they decrease the Descartes mutation score

How can it decrease your mutation score if you only add new test methods? This makes no sense since PIT guarantees the same number of mutants if you do not touch the source code (buisiness).

Do you still run the original test suite in addition to the amplified test methods you added? 

 You should double check if you don't have more errors(time out, memory errors etc..) between runs of **Descartes**.

Also, I suggest you to run both mutation analysis, baseline and amplified, on the same machine. From my experience, I could have a different number of mutants (total generated) from a node to another on the cluster, and so, you cannot compare the result.

> I think that there are much less live mutants (interesting targets for DSpot) with Descartes than Gregor.

Yes, I agree. And maybe mutants are less observable. 

For instance, **Descartes** removes the whole body of a void method. 
If the side-effect of the body is not observable through an existing getter, **DSpot** would never generate amplified test methods that kill this mutant.

**Comment by vmassol** [comment]
> How can it decrease your mutation score if you only add new test methods? This makes no sense since PIT guarantees the same number of mutants if you do not touch the source code (buisiness).

I guess because the new generated tests when using PIT/Gregor can have a lower mutation score as measure by Descartes since the oracle is using Gregor. I don't know. Is that supposed to be impossible?

We reported https://github.com/STAMP-project/dspot/issues/575 about this.

We did get a -1% mutation score but it seems the computation is not stable since when running it a few times more we got 0%

In any case so far we have 0% mutation score increase at best with PIT/Descartes.

**Comment by bbaudry** [comment]
As a strategy to move forward, I propose that @oscarlvp and @danglotb run an experiment
- take a XWiki module
- run Descartes to identify a list of pseudo-tested methods
- find the list of test cases that cover each pseudo-tested method
- run DSpot to specifically amplify these test cases

**Comment by oscarlvp** [comment]
If you want to execute Descartes (or Gregor) without modifying the `pom.xml` then you can use `PitMP`. It is quite convenient, I do it all the time.

Now, for `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default`  I ran descartes and found three *pseudo-tested* methods:
* [compare](  https://github.com/xwiki/xwiki-commons/blob/cac2ce2613868fd9ce7f102cde9681f6f8d2f953/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/embed/EmbeddableComponentManager.java#L663)
* [getPriority](https://github.com/xwiki/xwiki-commons/blob/cac2ce2613868fd9ce7f102cde9681f6f8d2f953/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/embed/EmbeddableComponentManager.java#L668)
* [handle](  https://github.com/xwiki/xwiki-commons/blob/cac2ce2613868fd9ce7f102cde9681f6f8d2f953/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/embed/ComposableLifecycleHandler.java#L35)

The first two are methods declared in an inline comparison implementation. Their code can be changed by `return 0` and `return 1` and no test case fails. `compare` is covered by two test cases in the `org.xwiki.component.embed.EmbeddableComponentManagerTest` and `getPriority` by only one of those same two test cases.

The third method, `handle` is the only method declared in the `ComposableLifecycleHandler` class. It is covered by 14 test cases,  11 of them belong to `org.xwiki.component.embed.EmbeddableComponentManagerTest`. If you remove the code of `handle` no test case fails.
So it seems that  `org.xwiki.component.embed.EmbeddableComponentManagerTest` is a good target for DSpot to amplify. Other test classes covering `handle` are `org.xwiki.component.embed.AmplEmbeddableComponentManagerTest`, and `org.xwiki.component.ProviderTest`.
