### ISSUE TITLE
Error with latest release on Sat4j: TestListener.ser not found

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#595]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [block]
- **Tool/Service/Component**: [Sat4j project]
- **Execution Environment**: [Linux Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

When executing DSpot on Sat4j, I have a file FileNotFoundException: 

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/assadm/OW2-Projects/Forks/sat4j/target/dspot/TestListener.ser does not exist.
	at eu.stamp_project.testrunner.runner.test.Loader.load(Loader.java:23)
	at eu.stamp_project.testrunner.runner.test.TestListener.load(TestListener.java:134)
	at eu.stamp_project.testrunner.EntryPoint.runTests(EntryPoint.java:183)
	at eu.stamp_project.testrunner.EntryPoint.runTests(EntryPoint.java:165)
	at eu.stamp_project.utils.compilation.TestRunner.runGivenTestMethods(TestRunner.java:61)
	at eu.stamp_project.utils.compilation.TestCompiler.compileAndRun(TestCompiler.java:99)
	at eu.stamp_project.utils.compilation.TestCompiler.compileRunAndDiscardUncompilableAndFailingTestMethods(TestCompiler.java:55)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:82)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:179)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:148)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:126)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:107)
	at eu.stamp_project.Main.run(Main.java:56)
	at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.io.FileNotFoundException: /home/assadm/OW2-Projects/Forks/sat4j/target/dspot/TestListener.ser does not exist.

#### Steps to reproduce

I built latest release, skipping tests as mentioned in issue #586:
mvn clean package -DskipTests

##### Properties file

project=.
targetModule=org.sat4j.core
filter=org.sat4j.core.*
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=dspot-out/
timeoutConstInMillis=10000
jvmArgs=['-Xmx2048m','-Xms1024m']

##### Command Line / Options

java -jar  /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @assadOW2 
I'm sorry, but I modified the way to give JVMArgs to DSpot.

Your actual properties needs an update:
```
jvmArgs=['-Xmx2048m','-Xms1024m']
```

You need now to use it as follow:
```
jvmArgs=-Xmx2048m,-Xms1024m
```

Could retry with the updated format?

If you still experience troubles, please provide the whole logs.

**Comment by assadOW2** [comment]
Thanks @danglotb , works fine now, I close the issue.
