### ISSUE TITLE
Timeout exception when amplifying SAT4J

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#628]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [ major]
- **Execution Environment**: [Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

DSpot throws a timeout exception when running on SAT4J

##### Properties file

```java
project=.
targetModule=org.sat4j.core
filter=org.sat4j.core.*
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=dspot-out/
timeoutConstInMillis=10000
jvmArgs=-Xmx2048m,-Xms1024m
```

##### Command Line / Options

```shell
java -jar  /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --test org.sat4j.BugSAT*  --generate-new-test-class --clean -s JacocoCoverageSelector --timeOut 30000
```

##### Trace
```
2018-10-30 15:20:12,085 INFO eu.stamp_project.utils.compilation.DSpotCompiler - Compiling with -proceedOnError -encoding UTF-8 -cp /home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/dspot/tmp_test_sources:/home/assadm/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/assadm/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/assadm/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/classes/:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/test-classes/:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/dspot/dependencies/: -d /home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/test-classes -1.8 -preserveAllLocals -noExit -enableJavadoc -proc:none /home/assadm/OW2-Projects/Forks/sat4j/org.sat4j.core/target/dspot/tmp_test_sources/org/sat4j/BugSAT117ModelIterator.java


2018-10-30 15:20:43,127 WARN eu.stamp_project.testrunner.EntryPoint - Timeout when running java -Xmx2048m -Xms1024m -classpath /home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/test-classes:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/classes/:/home/assadm/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/assadm/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/assadm/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/dspot/dependencies/:/home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar eu.stamp_project.testrunner.runner.test.TestRunner org.sat4j.BugSAT117ModelIterator testIt
2018-10-30 15:20:43,128 WARN eu.stamp_project.utils.compilation.TestRunner - Timeout during execution of org.sat4j.BugSAT117ModelIterator: testIt
2018-10-30 15:21:14,132 WARN eu.stamp_project.testrunner.EntryPoint - Timeout when running java -Xmx2048m -Xms1024m -classpath /home/assadm/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/assadm/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/assadm/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/classes/:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/test-classes/:/home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar:/home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar eu.stamp_project.testrunner.runner.coverage.JacocoRunner /home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/classes/:/home/assadm/OW2-Projects/Forks/sat4j/./org.sat4j.core/target/test-classes/ org.sat4j.BugSAT117ModelIterator 
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at eu.stamp_project.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:67)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:83)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:231)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$6(DSpot.java:210)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:211)
	at eu.stamp_project.Main.run(Main.java:66)
	at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at eu.stamp_project.testrunner.EntryPoint.runGivenCommandLine(EntryPoint.java:373)
	at eu.stamp_project.testrunner.EntryPoint.runCoverage(EntryPoint.java:308)
	at eu.stamp_project.testrunner.EntryPoint.runCoverageOnTestClasses(EntryPoint.java:212)
	at eu.stamp_project.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:61)
	... 13 more
```

**Comment by danglotb** [comment]
Hi @assadOW2 

I looked closer to this issue.

According to the traces, the test class that creates this problem is `org.sat4j.BugSAT117ModelIterato`. 
In this class, there is one test method:
```java
@Test
public void testIt() {
    Date begin = new Date();
    long beginTime = begin.getTime();

    Date now = new Date();
    while (now.getTime() - beginTime < 60000) {
        solve();
        now = new Date();
    }
}
```

On can see, that this test will run at least for 60 seconds( 60000ms) : `while (now.getTime() - beginTime < 60000)`.

I increase the timeout to 65000 (5000 + to be sure to not have the timeout) and I could amplify it (no amplify could increase the instruction coverage but DSpot completed the process). However, this long timeout seems to slow down the execution of DSpot.

I suggest you use: `--timeOut 65000`.

I consider this issue as invalid / misuse.

If you encounter any trouble with this, do not hesitate to reopen it! :-)

Best!
