### ISSUE TITLE
Dspot (PR #631) Maven failure

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#632]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Execution Environment**: [ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

This exception occurs only on PR#631 branch.

```
[ERROR] No plugin found for prefix 'org.pitest' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/assadm/.m2/repository), apache.snapshots (http://repository.apache.org/snapshots/), ow2-plugin-snapshot (http://repository.ow2.org/nexus/content/repositories/snapshots), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:127)
	at eu.stamp_project.dspot.selector.PitMutantScoreSelector.selectToKeep(PitMutantScoreSelector.java:109)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:85)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:231)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$6(DSpot.java:210)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:211)
	at eu.stamp_project.Main.run(Main.java:66)
	at eu.stamp_project.Main.main(Main.java:40)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:124)
	... 14 more
```

##### Properties file

```java
project=.
src=src/main/java/
testSrc=src/test/java/
```

##### Command Line / Options

```shell
java -jar  /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --test org.sat4j.BugSAT*  --generate-new-test-class --clean  --timeOut 30000 --verbose -m mutations.csv | tee -a trace.log
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @assadOW2 

Thank you for reporting this.

This PR should be now ready to be merged.

You probably pulled a little bit sooner than I expected. I suggest wait until it is merged, and build a new DSpot jar from the master branch or the [nexus repository](https://oss.sonatype.org/#nexus-search;quick~dspot) (It might take a while after the merge for the jar to be updated).

This PR will allow you to run DSpot with PIT/Descartes on SAT4J but you will have to set up properly your properties file.

The expected profile is like:

```xml
<profile>
            <id>descartes</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <version>1.4.0</version>
                        <configuration>
                            <verbose>true</verbose>
                            <mutationEngine>descartes</mutationEngine>
                            <outputFormats>
                                <value>HTML</value>
                                <value>CSV</value>
                                <value>ISSUES</value>
                                <value>METHODS</value>
                            </outputFormats>
                            <jvmArgs>
                                <value>-ea</value>
                                <value>
                                    -Dtest.prefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/
                                </value>
                                <value>
                                    -Dtest.pbprefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/
                                </value>
                            </jvmArgs>
                            <excludedTestClasses>
                                <value>org.sat4j.minisat.M2MiniLearningTest</value>
                                <value>org.sat4j.minisat.M2AtLeastTest</value>
                            </excludedTestClasses>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>eu.stamp-project</groupId>
                                <artifactId>descartes</artifactId>
                                <version>1.2.4</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

So you have to tell to DSpot each value.

```xml
<mutationEngine>descartes</mutationEngine>
```
This is the default mode of DSpot. To enable `gregor`, use the `--gregor` flag on the command line.

For the `outputFormats`, DSpot uses for now only CSV.

```xml
 <jvmArgs>
    <value>-ea</value>
    <value>-Dtest.prefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/</value>
    <value>-Dtest.pbprefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/</value>
</jvmArgs>
```

For this, use the property `jvmArgs` and split your arguments with a comma `,`:
`jvmArgs=-ea,-Dtest.prefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/,-Dtest.pbprefix=/home/bdanglot/workspace/sat4j/org.sat4j.core/src/test/testfiles/`

```xml
<excludedTestClasses>
    <value>org.sat4j.minisat.M2MiniLearningTest</value>
    <value>org.sat4j.minisat.M2AtLeastTest</value>
</excludedTestClasses>
```

Same as `jvmArgs`, but with the property `excludedClasses`:

`excludedClasses=org.sat4j.minisat.M2MiniLearningTest,org.sat4j.minisat.M2AtLeastTest`

**Comment by assadOW2** [comment]
@danglotb : thank you, it's now working. In attachment the trace of execution.
[trace.log](https://github.com/STAMP-project/dspot/files/2541790/trace.log)
