### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException in eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:77)

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#636]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot v1.2.2
- **Execution Environment**: CentOS
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
I've tested DSpot v1.2.2 in an previous experiment that failed with a NPE and that was reported before (see [experiment results](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810221352))
Now I get the following NPE when DSpot tries to generate a new pom.xml (I've read this is a new feature):

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:77)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runGoals(MavenAutomaticBuilder.java:152)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:50)
	at eu.stamp_project.program.InputConfiguration.initializeBuilder(InputConfiguration.java:220)
	at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:172)
	at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:93)
	at eu.stamp_project.options.JSAPOptions.parse(JSAPOptions.java:60)
	at eu.stamp_project.Main.main(Main.java:37)
Caused by: java.lang.NullPointerException
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.getFilter(DSpotPOMCreator.java:290)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createConfiguration(DSpotPOMCreator.java:237)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createPlugin(DSpotPOMCreator.java:164)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createBuild(DSpotPOMCreator.java:133)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createProfile(DSpotPOMCreator.java:120)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:65)
	... 7 more

```

##### Properties file

See dspot.properties and execution logs in this [folder](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201811051626)

##### Command Line / Options

DSpot CLI configuration:  `-i 3 -t eu.supersede.integration.api.adaptation.proxies.test.ModelRepositoryProxyTest -a AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier -s JacocoCoverageSelector --timeOut 120000 --max-test-amplified 200 --budgetizer NoBudgetizer --verbose
`

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
I've just tested with another IF component test suite and the same NPE on the eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:77) persists. It seems to be a possible bug introduced in this new v1.2.2. release.

**Comment by danglotb** [comment]
This should be fixed with #638

**Comment by tmortagne** [comment]
Just reproduce the same java.lang.NullPointerException with a freshly built dspot from master (f6f3741e3f48fc7febbce98f934f9cda002fffd0). Maybe it's because I use the plugin in the command line and not configured in my module.

```
tuska@tuska-G3-3779:~/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-context$ mvn clean eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.xwiki.commons:xwiki-commons-context >---------------
[INFO] Building XWiki Commons - Context 10.10-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ xwiki-commons-context ---
[INFO] Deleting /DATA/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-context/target
[INFO] 
[INFO] --- dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests (default-cli) @ xwiki-commons-context ---
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/eu/stamp-project/dspot/1.2.2-SNAPSHOT/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.resources/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.expressions/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.runtime/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.osgi/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.jobs/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.equinox.registry/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.equinox.preferences/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.contenttype/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.equinox.app/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.filesystem/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.text/maven-metadata.xml
Downloading from stamp-maven-repository-mvn-repo: https://stamp-project.github.io/stamp-maven-repository/org/eclipse/platform/org.eclipse.core.commands/maven-metadata.xml
[INFO] Path to runner Classes: /home/tuska/.m2/repository/eu/stamp-project/test-runner/1.1.1/test-runner-1.1.1-jar-with-dependencies.jar
[INFO] /home/tuska/.m2/repository/org/jacoco/org.jacoco.core/0.7.9/org.jacoco.core-0.7.9.jar
[INFO] /home/tuska/.m2/repository/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
[INFO] /home/tuska/.m2/repository/eu/stamp-project/test-runner/1.1.1/test-runner-1.1.1-jar-with-dependencies.jar
[WARNING] : unknown automatic builder specified in configuration, going to default.
[INFO] Default: provided Maven automatic builder.
[WARNING] You gave an empty filter. To use PIT, it is recommend to specify a filter, at least, the top package of your program, otherwise, PIT may take a long time or could not be run.
[WARNING] Trying to compute the top package of the project...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.162 s
[INFO] Finished at: 2018-11-06T12:03:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests (default-cli) on project xwiki-commons-context: Execution default-cli of goal eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests (default-cli) on project xwiki-commons-context: Execution default-cli of goal eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:281)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom (DSpotPOMCreator.java:77)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runGoals (MavenAutomaticBuilder.java:152)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.compileAndBuildClasspath (MavenAutomaticBuilder.java:50)
    at eu.stamp_project.program.InputConfiguration.initializeBuilder (InputConfiguration.java:220)
    at eu.stamp_project.program.InputConfiguration.initialize (InputConfiguration.java:124)
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:232)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.NullPointerException
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.getFilter (DSpotPOMCreator.java:290)
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createConfiguration (DSpotPOMCreator.java:237)
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createPlugin (DSpotPOMCreator.java:164)
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createBuild (DSpotPOMCreator.java:133)
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createProfile (DSpotPOMCreator.java:120)
    at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom (DSpotPOMCreator.java:65)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runGoals (MavenAutomaticBuilder.java:152)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.compileAndBuildClasspath (MavenAutomaticBuilder.java:50)
    at eu.stamp_project.program.InputConfiguration.initializeBuilder (InputConfiguration.java:220)
    at eu.stamp_project.program.InputConfiguration.initialize (InputConfiguration.java:124)
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:232)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by jesus-gorronogoitia** [comment]
Fixed with new patch #638 Closing

**Comment by tmortagne** [comment]
I confirm no more nullpointer with the previous command after a new pull, I tough it was already merged when I built.

**Comment by danglotb** [comment]
Hi, glad to hear that. Thank you!
