### ISSUE TITLE
DSpot null pointer exception

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#637]
#### Characteristics

- **Issue Type**:  bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: [ DSpot, 1.2.2 ]
- **Execution Environment**: Linux
- **Reporter**: [ Ricardo Tejada, ricardo.tejada.external@atos.net ]

#### Description

DSpot produces the following exception working with dhell project 

2018-11-05 18:03:44,842 INFO eu.stamp_project.testrunner.EntryPoint - Path to runner Classes: /home/ricardo/Repositorios/DSpotSource/dspot/dspot/target/dspot-1.2.2-SNAPSHOT-jar-with-dependencies.jar
2018-11-05 18:03:44,849 INFO eu.stamp_project.testrunner.EntryPoint - /home/ricardo/Repositorios/DSpotSource/dspot/dspot/target/dspot-1.2.2-SNAPSHOT-jar-with-dependencies.jar
2018-11-05 18:03:44,850 INFO eu.stamp_project.testrunner.EntryPoint - /home/ricardo/Repositorios/DSpotSource/dspot/dspot/target/dspot-1.2.2-SNAPSHOT-jar-with-dependencies.jar
2018-11-05 18:03:44,850 INFO eu.stamp_project.testrunner.EntryPoint - /home/ricardo/Repositorios/DSpotSource/dspot/dspot/target/dspot-1.2.2-SNAPSHOT-jar-with-dependencies.jar
2018-11-05 18:03:44,850 WARN eu.stamp_project.program.InputConfiguration - No builder has been specified.
2018-11-05 18:03:44,851 WARN eu.stamp_project.program.InputConfiguration - Using Maven as a default builder.
2018-11-05 18:03:44,851 WARN eu.stamp_project.program.InputConfiguration - You can use the command-line option --automatic-builder
2018-11-05 18:03:44,851 WARN eu.stamp_project.program.InputConfiguration - or the properties automaticBuilderName to configure it.
2018-11-05 18:03:44,852 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2018-11-05 18:03:44,951 WARN eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator - You gave an empty filter. To use PIT, it is recommend to specify a filter, at least, the top package of your program, otherwise, PIT may take a long time or could not be run.
2018-11-05 18:03:44,951 WARN eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator - Trying to compute the top package of the project...
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:77)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runGoals(MavenAutomaticBuilder.java:152)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:50)
	at eu.stamp_project.program.InputConfiguration.initializeBuilder(InputConfiguration.java:220)
	at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:172)
	at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:93)
	at eu.stamp_project.options.JSAPOptions.parse(JSAPOptions.java:60)
	at eu.stamp_project.Main.main(Main.java:37)
Caused by: java.lang.NullPointerException
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.getFilter(DSpotPOMCreator.java:290)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createConfiguration(DSpotPOMCreator.java:237)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createPlugin(DSpotPOMCreator.java:164)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createBuild(DSpotPOMCreator.java:133)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createProfile(DSpotPOMCreator.java:120)
	at eu.stamp_project.automaticbuilder.maven.DSpotPOMCreator.createNewPom(DSpotPOMCreator.java:65)
	... 7 more 

##### Properties file

```java
project= /home/.../dhell
src=src/main/java/
testSrc=src/test/java/
javaVersion=8
outputDirectory=dspot-out/
```

##### Command Line / Options

```shell
java -jar target/dspot-1.2.2-jar-with-dependencies.jar \
-p myPropertiesFile.properties
-a MethodAdd
-s JacocoCoverageSelector
-i 1
```

**Comment by danglotb** [comment]
Hi @RicardoTej 

According to the stack trace, this issue seems to be a duplicate of #636.

Please, retry after the merge of #638.

**Comment by RicardoTej** [comment]
Fixed
Thank you !
