### ISSUE TITLE
java.io.FileNotFoundException: File does not exist: /home/stamp/Git/Supersede/integration/IF/API/eu.supersede.if.api/./.dspot_pom.xml

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#643]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot v1.2.2
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot v1.2.2 works well in some Supersede IF test classes where before it didn't. DSpot completes the execution, generates test cases and reports coverage amplification, but upon finalization, it triggers an exception as it seems trying to delete a non-existing pom.xml file (I guess the one it thinks it has generated, but it hasn't). The exception is the following:

```
java.io.FileNotFoundException: File does not exist: /home/stamp/Git/Supersede/integration/IF/API/eu.supersede.if.api/./.dspot_pom.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2377)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.delete(MavenAutomaticBuilder.java:108)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.reset(MavenAutomaticBuilder.java:120)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:270)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$6(DSpot.java:223)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:224)
	at eu.stamp_project.Main.run(Main.java:70)
	at eu.stamp_project.Main.main(Main.java:41)

```
##### Properties file

See [dspot.properties](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-ReturnValueAmplifier-NullifierAmplifier/201811061456/dspot.properties)

##### Command Line / Options

DSpot CLI configuration:  
`-i 3 -t eu.supersede.integration.api.feedback.proxies.test.FeedbackRepositoryProxyTest -a AllLiteralAmplifiers:ReturnValueAmplifier:NullifierAmplifier -s JacocoCoverageSelector --timeOut 240000 --max-test-amplified 200 --budgetizer NoBudgetizer --verbose`

#### Other files and URLs
See execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-ReturnValueAmplifier-NullifierAmplifier/201811061456/dspot.log.tgz)

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

Thank you for reporting this issue. In fact, only when using the PitMutantScoreSelector the pom is generated and used.

I'm gonna fix this ASAP.

**Comment by danglotb** [comment]
Now, DSpot won't try to delete the pom if it does not need to generate it, and thus the experienced error won't appear anymore.
