### ISSUE TITLE
Pitest crash when it is executed with gradle

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/dspot#657]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [Dspot, 1.2.1]
- **Execution Environment**: [Ubuntu, 16.04]
- **Reporter**: [Mael Audren, mael.audren@activeeon.com]

#### Description

When executing Dspot on the catalog project, an exception occurs when pitest should be executed. All the details are available on https://github.com/STAMP-project/dspot-usecases-output/tree/master/activeeon/catalog/8.2.0#pitest-exception

#### Steps to reproduce

```bash
git clone https://github.com/ow2-proactive/catalog
git fetch origin master
git checkout 8.2.X
```
Then download Dspot release 1.2.1 and add the properties file below in the project root.
Finally launch the command : 
```bash
java -jar dspot-1.2.1-jar-with-dependencies.jar --path-to-properties dspot.properties --automatic-builder GradleBuilder -t org.ow2.proactive.catalog.dto.*
```

##### dspot.properties

```
# Relative path to the project root.                                                                                                                                                                         
project=.
# Relative path to the source project from this properties file                                                                                                                                              
src=src/main/java/
# Relative path to the test source project from this properties file                                                                                                                                         
testSrc=src/test/java/
# Java version used                                                                                                                                                                                          
javaVersion=8
# (Optional) Path to the output folder, default to "output_diversify"                                                                                                                                        
outputDirectory=time/
# (Optional) Filter on the package name containing tests to be amplified ("example" => "example.*")                                                                                                          
#filter=org.ow2.proactive.catalog.dto.*                                                                                                                                                                      
classes=build/classes/main/
testClasses=build/classes/test/
```

**Comment by MaelAudren** [comment]
@danglotb if I remember well you told me that there is a way to provide to Dspot the PIT report. Maybe it could be a workaround.

**Comment by danglotb** [comment]
Hi @MaelAudren 

It is because your `filter` property is commented. 

When using maven, this property is not required, but for gradle it is.

To fix your issue, just uncomment (by removing the `#` at the begin of the line) your `filter` property.

> @danglotb if I remember well you told me that there is a way to provide to Dspot the PIT report. Maybe it could be a workaround.

In fact, if you have already run PIT on your project and have the CSV file report, you can give it to DSpot with:

```java
  [(-m|--path-pit-result) <./path/to/mutations.csv>]
        [optional, expert mode] specify the path to the .csv of the original
        result of Pit Test. If you use this option the selector will be forced
        to PitMutantScoreSelector
```

to obtain the CSV file, you have to enable the CSV output format, add this to your `build.gradle`:

```gradle
outputFormats = ['CSV','HTML']
```

then, save the `.csv` file report. 

I'll now explain a little bit why doing this is reducing the execution time of DSpot.

When you run DSpot in default mode, it uses the `PitMutantScoreSelector`. What happens is, that DSpot runs PIT **before** the amplification. It gathers all the killed and alive mutants. This first run of PIT allows to have a baseline, and it is computed for the whole test suite, _i.e._ every test classes that PIT can found.

Then, for each amplified test method, it runs PIT and gathers the killed mutants. If in this list of killed mutant (by the amplified test method) there are some mutants that remained alive when using the original test suite (_i.e._ the baseline), one can say that the amplified test method improves the mutation score, since it kills a mutant that was not killed by the original test suite.

The point is, we all know that DSpot takes time and memory, and thus, we tend to amplify not the whole test suite, but test class by test class. That is to say, we make a run of DSpot for every test class. So, each time we run DSpot, it recomputes the baseline, to be able to compare the mutation score of the amplified test methods to the original mutation score.

The option `  [(-m|--path-pit-result) <./path/to/mutations.csv>]` allows you to skip the first PIT's execution since DSpot will read the baseline from the CSV file, which is much more efficient than executing PIT.

To conclude, I advise you to amplify test class by test class (a fortiori if you use Input amplification: `--amplifiers` command line option) and thus provide to DSpot this pre-computed baseline.

PS: no matter the mutation engine used by PIT (descartes or the default), DSpot does the same.

**Comment by danglotb** [comment]
Okay, I think that the problem is that you have twice the same task:

```
pitest {
   targetClasses = ['com.xxxx.mxx.dr.*']
   enableDefaultIncrementalAnalysis = true
   outputFormats = ['CSV','HTML']
   timeoutConstInMillis = 10000
   jvmArgs = ['-Xmx2048m','-Xms1024m']
}

apply plugin: 'info.solidsoft.pitest'

pitest {
    targetClasses = ['com.xxxx.mxx.dr.*']
    enableDefaultIncrementalAnalysis = true
    reportDir = 'build/pit-reports'
    outputFormats = ['CSV','HTML']
    pitestVersion = '1.4.0'
    timeoutConstInMillis = 10000
    jvmArgs = ['-Xmx2048m','-Xms1024m']
    mutationEngine = 'descartes'
}
```
 I guess that you added the first `pitest` manually, and the second one has been generated by `DSpot`. (Without crash, DSpot cleans up your gradle file...).

What I can propose for now, it that you try to remove both task from your `build.gradle` file, and retry.

I'm gonna make a pull request to avoid such scenario. 

Best!

**Comment by lfcortes12** [comment]
I tested it again removing pitest task but I got the same issue :(

Thanks in advance.

**Comment by danglotb** [comment]
Okay, could provide the whole project. I need it to debug DSpot. Thank you.

**Comment by lfcortes12** [comment]
@danglotb sorry, unfortunately, I can not share the project due to legal constraints :(. But I can say that is a Gradle project with two submodules.

Regards,

**Comment by danglotb** [comment]
Hi @lfcortes12 

> sorry, unfortunately, I can not share the project due to legal constraints :(.

Okay, we will try through GitHub then.

> But I can say that is a Gradle project with two submodules.

That is a good clue. According to your first post, your properties file is:

```java
project=base-tool/service/
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=target/trash/
jvmArgs=-Xmx2048m,-Xms1024m
filter=com.xxxx.mxx.dr.*
```

Since DSpot works at the module level, you have to precise the module you want to amplify.
To do this, you have to add a dedicated property, named `targetModule`.

For instance, imagine you have the following hierarchy:

```
topModule/
|  build.gradle
├── module-1/
│   | build.gradle
│   ├── module-1-1
│   │     ├── src/
│   │     |  build.gradle
│   ├── module-1-2
│   │     ├── src/
├── module-2/
│ ....
```
and you want to amplify module-1-1.

then you need to specify the following properties:

```java
project=<absolute_path>/topModule
targetModule=module-1/module-1-1/
```

DSpot uses the value of `targetModule` by concatening it to the property `project` and finds the absolute path to the targeted module. Last point, you should keep your others properties. 

Eventually, you end up with something like:

```java
project=base-tool/service/
targetModule=<relative_path_to_root_module_from_project_property>
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=target/trash/
jvmArgs=-Xmx2048m,-Xms1024m
filter=com.xxxx.mxx.dr.*
```

However, I did not develop the gradle support for DSpot. I cannot guarantee you that DSpot supports gradle multi-module project.

Let's find out together.

Best.

**Comment by lfcortes12** [comment]
Tested as you suggested but I got same error

**Comment by danglotb** [comment]
Could you provide me the whole stack trace?

@MaelAudren Did you solve your issue?

**Comment by lfcortes12** [comment]
@danglotb the stack trace:

`ava.lang.RuntimeException: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.7-bin.zip'.
        at eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder.runTasks(GradleAutomaticBuilder.java:113)
        at eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder.runPit(GradleAutomaticBuilder.java:94)
        at eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder.runPit(GradleAutomaticBuilder.java:85)
        at eu.stamp_project.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:59)
        at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:97)
        at eu.stamp_project.Main.run(Main.java:53)
        at eu.stamp_project.Main.main(Main.java:41)
Caused by: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.7-bin.zip'.
        at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
        at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
        at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Unknown Source)
        at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
        at eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder.runTasks(GradleAutomaticBuilder.java:111)
        ... 6 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':base-tool-service:pitest'.
        at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
        at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
        at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:143)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:115)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
        at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:53)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:42)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:61)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':base-tool-service:pitest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:59)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:130)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:46)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:336)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:210)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
        ... 64 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_181\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:36)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:76)
        at info.solidsoft.gradle.pitest.PitestTask.exec(PitestTask.groovy:205)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 107 more
2018-11-21 10:37:02,487 INFO eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder - Restoring original Gradle build file...
2018-11-21 10:37:02,488 INFO eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder - Deleting modified (with injected task) Gradle build file...
2018-11-21 10:37:02,492 INFO eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilder - Renaming original Gradle build file from C:\dev\git\base-tool-tool\service\\build.gradle.orig to C:\dev\git\base-tool-tool\service\\build.gradle...
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: C:\dev\git\base-tool-tool\service\build\pit-reports\201811211037\mutations.csv (The system cannot find the file specified)
        at eu.stamp_project.mutant.pit.PitResultParser.parse(PitResultParser.java:92)
        at eu.stamp_project.mutant.pit.PitResultParser.parseAndDelete(PitResultParser.java:41)
        at eu.stamp_project.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:60)
        at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:97)
        at eu.stamp_project.Main.run(Main.java:53)
        at eu.stamp_project.Main.main(Main.java:41)
Caused by: java.io.FileNotFoundException: C:\dev\git\base-tool-tool\service\build\pit-reports\201811211037\mutations.csv (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at eu.stamp_project.mutant.pit.PitResultParser.parse(PitResultParser.java:59)
        ... 5 more`

**Comment by danglotb** [comment]
Thank you @lfcortes12 
```
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_181\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:36)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:76)
        at info.solidsoft.gradle.pitest.PitestTask.exec(PitestTask.groovy:205)
```
Something went wrong when DSpot executed PIT.

Were you able to execute PIT out of DSpot?

**Comment by lfcortes12** [comment]
@danglotb  It works normally.

**Comment by MaelAudren** [comment]
@danglotb I manage to use PIT report using the -t command and by adding the filter parameter in the properties. 
Maybe I misunderstood something however when I use filter I doesn't manage to reduce the number of class analyzed. In order to select specific class I have to use the option -t and specify the package/class to use. Is it normal ?

**Comment by danglotb** [comment]
Hi @MaelAudren 

>  when I use filter I doesn't manage to reduce the number of class analyzed.

The `filter` property is ONLY used by PIT (through DSpot). The  `filter` is simply forwarded to the option targetClasses of PIT. Excerpt of the PIT's documentation:

> targetClasses
> The classes to be mutated. This is expressed as a list of globs.
> 
> For example
> 
> <targetClasses>
>     <param>com.mycompany.*</param>
> </targetClasses>
> or
> 
> <targetClasses>
>     <param>com.mycompany.package.*</param>
>     <param>com.mycompany.packageB.Foo*</param>
>     <param>com.partner.*</param>
> </targetClasses>
> If no targetClasses are supplied pitest will automatically determine what to mutate.

If you do not provide this value, PIT uses `<groupID>.<artifactID>.*`.

The `(-t|--test)` flag is used by DSpot to know which test class you want to amplify.

To sum up, the `filter` propertty is used by PIT to know which classes to mutate and the `(-t|--test)` flag is used by DSpot to know which test classes to amplified.

> @danglotb It works normally.

I am sorry @lfcortes12 I cannot do much more. I would need more information around your project.

I propose you to open a dedicated issue.

Best.

**Comment by MaelAudren** [comment]
@danglotb thanks a lot for all the clarification.
