### ISSUE TITLE
Error when using the Maven plugin when trying to delete the dspot_pom.xml file

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#669]
Execution with: `mvn dspot:amplify-unit-tests`.

Error:

```
[WARNING] Something bad happened when trying to delete /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local/../../../xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local/.dspot_pom.xml.
java.io.FileNotFoundException: File does not exist: /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local/../../../xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local/.dspot_pom.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2377)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.delete(MavenAutomaticBuilder.java:106)
	at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.reset(MavenAutomaticBuilder.java:118)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:270)
	at eu.stamp_project.dspot.DSpot._amplifyTestClass(DSpot.java:234)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot._amplifyTestClasses(DSpot.java:230)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:149)
	at eu.stamp_project.Main.run(Main.java:60)
	at eu.stamp_project.DSpotMojo.execute(DSpotMojo.java:279)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Ignoring, moving forward...
```

My config:

```
        <plugin>
          <groupId>org.pitest</groupId>
          <artifactId>pitest-maven</artifactId>
          <version>1.4.0</version>
        </plugin>
        <plugin>
          <groupId>eu.stamp-project</groupId>
          <artifactId>dspot-maven</artifactId>
          <version>1.2.1</version>
          <configuration>
            <clean>true</clean>
            <descartes>true</descartes>
            <verbose>true</verbose>
            <withComment>true</withComment>
            <generateNewTestClass>true</generateNewTestClass>
            <pathToProperties>./dspot.properties</pathToProperties>
          </configuration>
        </plugin>
```

Would be great to not throw this exception when the file doesn't exist. BTW why doesn't it exist in my case, is that normal?

Thanks!

**Comment by danglotb** [comment]
Hi @vmassol 

I'm sorry I'm not able to obtain the same stack trace (I tried on a small project).

Could you provide me the content of your properties file and maybe the artifact on which you are trying to execute the DSpot's maven plugin?

Thank you.

**Comment by vmassol** [comment]
Hi @danglotb 

* DSpot 1.2.1
* XWiki module: xwiki-commons/xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local
* Dspot properties file:

```
project=../../../
targetModule=xwiki-commons-core/xwiki-commons-observation/xwiki-commons-observation-local
src=src/main/java/
testSrc=src/test/java/
testResources=src/test/resources/
javaVersion=8
outputDirectory=output
filter=org.xwiki.*
srcResources=src/main/resources/
```
* DSpot Maven plugin config:

```
      <plugin>
          <groupId>eu.stamp-project</groupId>
          <artifactId>dspot-maven</artifactId>
          <version>1.2.1</version>
          <configuration>
            <clean>true</clean>
            <descartes>true</descartes>
            <verbose>true</verbose>
            <withComment>true</withComment>
            <generateNewTestClass>true</generateNewTestClass>
            <pathToProperties>./dspot.properties</pathToProperties>
          </configuration>
        </plugin>
```

**Comment by vmassol** [comment]
FTR just tried again and got the same error in the logs.

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
