### ISSUE TITLE
FileNotFoundException: target/dspot/observations.ser

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#715]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [block]
- **Tool/Service/Component**: [lutece-core project, fork available in STAMP-project]
- **Execution Environment**: [Linux ubun]tu 18.04
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.orgl]

#### Description

When executing DSpot on lutece-core, I have a file FileNotFoundException:

2019-02-18 10:45:32,758 INFO eu.stamp_project.Main - Amplification succeed.
2019-02-18 10:45:32,759 INFO eu.stamp_project.Main - Elapsed time 44699 ms
2019-02-18 10:45:32,759 WARN eu.stamp_project.utils.report.GlobalReport - DSpot encountered some errors during amplification.
2019-02-18 10:45:32,761 WARN eu.stamp_project.utils.report.GlobalReport - DSpot encountered 1 error(s) during amplification.
Something bad happened during assertion amplification
java.lang.RuntimeException: java.io.FileNotFoundException: target/dspot/observations.ser (Aucun fichier ou dossier de ce type)
	at eu.stamp_project.compare.ObjectLog.load(ObjectLog.java:254)
	at eu.stamp_project.compare.ObjectLog.getObservations(ObjectLog.java:216)
	at eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator.addAssertions(MethodsAssertGenerator.java:122)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.innerAssertionAmplification(AssertGenerator.java:132)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.assertionAmplification(AssertGenerator.java:72)
	at eu.stamp_project.dspot.Amplification.assertionsAmplification(Amplification.java:187)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:96)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:274)
	at eu.stamp_project.dspot.DSpot._amplifyTestClass(DSpot.java:265)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at eu.stamp_project.dspot.DSpot._amplifyTestClasses(DSpot.java:261)
	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:147)
	at eu.stamp_project.Main.run(Main.java:59)
	at eu.stamp_project.Main.main(Main.java:41)
Caused by: java.io.FileNotFoundException: target/dspot/observations.ser (Aucun fichier ou dossier de ce type)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at eu.stamp_project.compare.ObjectLog.load(ObjectLog.java:246)
	... 19 more

#### Steps to reproduce

Not so easy: the projects requires a MySQL database, and some tricks so DSpot runs (config files generated in target/ are required for tests, so that "mvn test" does work only after a build phase, namely "mvn clean lutece:exploded" ... but dspot seems to clean before testing ? it is unclear, but not related to current issue, as I managed to provide the proper config by hand - dspot amplification seems to run fine).

##### Properties file

```java
#relative path to the source project from the project properties
src=src/java/
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#filter used to amplify specific test cases
filter=fr.paris.lutece.*
excludedClasses=fr.paris.lutece.portal.*
#path to the output folder
outputDirectory=target/trash/
# Constant amount of additional time to allow a test to run for
# before considering it to be stuck in an infinite loop
timeoutConstInMillis=10000
#Argument string to use when PIT launches child processes. This is most commonly used
# to increase the amount of memory available to the process,
# but may be used to pass any valid JVM argument.
# Use commas to separate multiple arguments, and put them within brackets
jvmArgs=-Xmx2048m,-Xms1024m

#Mutators to apply when using Descartes Mode
descartesMutators='A'

```

##### Command Line / Options

```shell
java -jar dspot/dspot/target/dspot-2.0.1-SNAPSHOT-jar-with-dependencies.jar -p ./dspot.properties --verbose
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @gibello 

Yes, first of all, DSpot runs `mvn clean test -DskipTests dependency:build-classpath` to clean, download the dependencies and build a correct classpath.

I guess that the `mvn clean lutece:exploded` result is clean by the command exposed above.

Plus, DSpot is using a classical java command line to execute the test, and not a maven goal, which is problematic according to @assadOW2 and #704.

I'm working on a pull request #714 in order to use maven goals to execute the tests. The user could be able to specify its own additional goals, like yours: `lutece:exploded`.

However, I have a question. Must this goal be run each time we execute the test or just once before multiple executions? Is it problematic if DSpot execute this goal each time he wants to execute the tests? 
with for example: `mvn lutece:exploded test -Dtest=temporaryTestGeneratedByDSpot1...`

Because during the DSpot's process, we need to execute the test several times.

**Comment by danglotb** [comment]
Could you retry by following the instructions in #704 ? Thank you! I'm closing this issue since it is duplicated. We keep going on #704.
