### ISSUE TITLE
PitMutantSelector fails because test suite not green... but mvn test passes

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#724]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [dspot maven plugin]
- **Execution Environment**: [Linux ubuntu 18.04, Java8]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

Testing dspot on OW2 authzforce project (https://gitlab.ow2.org/authzforce/core).

When using PitMutantSelector, the build fails, reporting "all tests did not pass without mutation".

But "mvn tests" passes (build success).

#### Steps to reproduce

Add this to pom in authzforce/core (build/plugins section):
```xml
        <plugin>
           <groupId>eu.stamp-project</groupId>
           <artifactId>dspot-maven</artifactId>
           <version>2.0.1-SNAPSHOT</version>
           <configuration>
            <src>pdp-engine/src/main/java</src>
            <testSrc>pdp-engine/src/test/java</testSrc>
            <testCriterion>PitMutantScoreSelector</testCriterion>
            <!--amplifiers>
              <amplifier>MethodAdd</amplifier>
            </amplifiers-->
            <outputDirectory>target/trash</outputDirectory>
            <verbose>true</verbose>
            <generate-new-test-class>true</generate-new-test-class>
            <with-comment>true</with-comment>
            <use-maven-to-exe-test>true</use-maven-to-exe-test>
           </configuration>
         </plugin>
```

Then "mvn dspot:amplify-unit-tests".

Error report:

```
[INFO] Mutating from /home/gibello/STAMP/STAMP-project/authzforce/core/pdp-engine/target/classes
12:25:24 PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
12:25:25 PIT >> INFO : Sending 245 test classes to minion
12:25:25 PIT >> INFO : Sent tests to minion
12:25:25 PIT >> INFO : MINION : 12:25:25 PIT >> INFO : Checking environment

12:25:33 PIT >> INFO : MINION : 12:25:33 PIT >> INFO : Found  1385 tests

12:25:33 PIT >> INFO : MINION : 12:25:33 PIT >> INFO : Dependency analysis reduced number of potential tests by 0
12:25:33 PIT >> INFO : 1385 tests received

12:25:33 PIT >> INFO : MINION : 12:25:33 PIT >> SEVERE : Description [testClass=org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest, name=test[2: null; user=null; sys=/tmp/authzforce/c -> {5}](org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest)]
jav
12:25:33 PIT >> INFO : MINION : a.lang.IllegalArgumentException: Could not resolve placeholder 'AUTHZFORCE_DATA_DIR' in value "${AUTHZFORCE_DATA_DIR}/c"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.uti
12:25:33 PIT >> INFO : MINION : l.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.ow2.authzforce.core.pdp.impl.DefaultEnvironmentProperties.replacePlaceholders(DefaultEnvironmentProperties.java:88)
	at org.ow2.authzforce.core.pdp.impl.test.Defaul
12:25:33 PIT >> INFO : MINION : tEnvironmentPropertiesTest.test(DefaultEnvironmentPropertiesTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAcc
12:25:33 PIT >> INFO : MINION : essorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run
12:25:33 PIT >> INFO : MINION : (ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.ev
12:25:33 PIT >> INFO : MINION : aluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.j
12:25:33 PIT >> INFO : MINION : ava:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(
12:25:33 PIT >> INFO : MINION : ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26
12:25:33 PIT >> INFO : MINION : )
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(Parent
12:25:33 PIT >> INFO : MINION : Runner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adap
12:25:33 PIT >> INFO : MINION : ter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
	at org.pitest.testapi.ex
12:25:33 PIT >> INFO : MINION : ecute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)

12:25:33 PIT >> INFO : MINION : 12:25:33 PIT >> SEVERE : Description [testClass=org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest, name=test[3: {PARENT_DIR=path/to}; user={sys.prop=zx}; sys=/tmp/authzforce/b/path/to/c/zx/d -> {5}](org.ow2.authzforce.core.pdp.impl.tes
12:25:33 PIT >> INFO : MINION : t.DefaultEnvironmentPropertiesTest)]
java.lang.IllegalArgumentException: Could not resolve placeholder 'AUTHZFORCE_DATA_DIR' in value "${AUTHZFORCE_DATA_DIR}/b/${PARENT_DIR}/c/${sys.prop}/d"
	at org.springframework.util.PropertyPlaceholderHelper.parseStrin
12:25:33 PIT >> INFO : MINION : gValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.ow2.authzforce.core.pdp.impl.DefaultEnvironmentProperties.replacePlaceholders(DefaultEnvironme
12:25:33 PIT >> INFO : MINION : ntProperties.java:88)
	at org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest.test(DefaultEnvironmentPropertiesTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke
12:25:33 PIT >> INFO : MINION : (NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMetho
12:25:33 PIT >> INFO : MINION : d.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(Invoke
12:25:33 PIT >> INFO : MINION : Method.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.
12:25:33 PIT >> INFO : MINION : junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren
12:25:33 PIT >> INFO : MINION : (ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runCh
12:25:33 PIT >> INFO : MINION : ild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(Paren
12:25:33 PIT >> INFO : MINION : tRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.pitest.junit.adapter.CustomRunn
12:25:33 PIT >> INFO : MINION : erExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.contain
12:25:33 PIT >> INFO : MINION : ers.UnContainer.execute(UnContainer.java:31)
	at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	at org.pit
12:25:33 PIT >> INFO : MINION : est.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)

12:25:37 PIT >> SEVERE : Description [testClass=org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest, name=test[2: null; user=null; sys=/tmp/authzforce/c -> {5}](org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest)] did not pass without mutation.
12:25:37 PIT >> SEVERE : Description [testClass=org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest, name=test[3: {PARENT_DIR=path/to}; user={sys.prop=zx}; sys=/tmp/authzforce/b/path/to/c/zx/d -> {5}](org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest)] did not pass without mutation.
12:25:48 PIT >> INFO : Calculated coverage in 23 seconds.
/[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.868 s
[INFO] Finished at: 2019-02-26T12:25:48+01:00
[INFO] Final Memory: 12M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:mutationCoverage (default-cli) on project authzforce-ce-core-pdp-engine: Execution default-cli of goal org.pitest:pitest-maven:1.4.0:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.ow2.authzforce:authzforce-ce-core .............. SUCCESS [01:49 min]
[INFO] org.ow2.authzforce:authzforce-ce-core-pdp-engine ... FAILURE [01:43 min]
[INFO] org.ow2.authzforce:authzforce-ce-core-pdp-testutils  SKIPPED
[INFO] org.ow2.authzforce:authzforce-ce-core-pdp-io-xacml-json SKIPPED
[INFO] org.ow2.authzforce:authzforce-ce-core-pdp-cli ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:33 min
[INFO] Finished at: 2019-02-26T12:25:48+01:00
[INFO] Final Memory: 48M/505M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal eu.stamp-project:dspot-maven:2.0.1-SNAPSHOT:amplify-unit-tests (default-cli) on project authzforce-ce-core-pdp-engine: Execution default-cli of goal eu.stamp-project:dspot-maven:2.0.1-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose) -> [Help 1]


Exception stack traces (maven -e option) follow:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal eu.stamp-project:dspot-maven:2.0.1-SNAPSHOT:amplify-unit-tests (default-cli) on project authzforce-ce-core-pdp-engine: Execution default-cli of goal eu.stamp-project:dspot-maven:2.0.1-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal eu.stamp-project:dspot-maven:2.0.1-SNAPSHOT:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:304)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit (MavenAutomaticBuilder.java:144)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit (MavenAutomaticBuilder.java:150)
    at eu.stamp_project.dspot.selector.PitMutantScoreSelector.init (PitMutantScoreSelector.java:84)
    at eu.stamp_project.dspot.Amplification.amplification (Amplification.java:87)
    at eu.stamp_project.dspot.DSpot._amplify (DSpot.java:274)
    at eu.stamp_project.dspot.DSpot._amplifyTestClass (DSpot.java:265)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:499)
    at eu.stamp_project.dspot.DSpot._amplifyTestClasses (DSpot.java:261)
    at eu.stamp_project.dspot.DSpot.amplifyAllTests (DSpot.java:147)
    at eu.stamp_project.Main.run (Main.java:59)
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:302)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit (MavenAutomaticBuilder.java:141)
    at eu.stamp_project.automaticbuilder.maven.MavenAutomaticBuilder.runPit (MavenAutomaticBuilder.java:150)
    at eu.stamp_project.dspot.selector.PitMutantScoreSelector.init (PitMutantScoreSelector.java:84)
    at eu.stamp_project.dspot.Amplification.amplification (Amplification.java:87)
    at eu.stamp_project.dspot.DSpot._amplify (DSpot.java:274)
    at eu.stamp_project.dspot.DSpot._amplifyTestClass (DSpot.java:265)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:499)
    at eu.stamp_project.dspot.DSpot._amplifyTestClasses (DSpot.java:261)
    at eu.stamp_project.dspot.DSpot.amplifyAllTests (DSpot.java:147)
    at eu.stamp_project.Main.run (Main.java:59)
    at eu.stamp_project.DSpotMojo.execute (DSpotMojo.java:302)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by danglotb** [comment]
This error occurs when DSpot tries to compute the baseline for amplification, _i.e._ the mutation score of the original test suite (before amplification).

It seems that `authzforce` is a multi-module project. DSpot and PIT work on module level and cannot be applied on the whole project.

I tried to apply DSpot on `pdp-engine`, but still got the same errors.

So I ran manually PIT (because DSpot fails because PIT fails) with: `mvn org.pitest:pitest-maven:mutationCoverage`

And checked the first error:

```
13:37:30 PIT >> INFO : MINION : 13:37:30 PIT >> SEVERE : Description [testClass=org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest, name=test[2: null; user=null; sys=/tmp/authzforce/c -> {5}](org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest)]
jav
13:37:30 PIT >> INFO : MINION : a.lang.IllegalArgumentException: Could not resolve placeholder 'AUTHZFORCE_DATA_DIR' in value "${AUTHZFORCE_DATA_DIR}/c"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.uti
```

Seems like that the first test that fails is `org.ow2.authzforce.core.pdp.impl.test.DefaultEnvironmentPropertiesTest#test`.

Looking into the [test source](https://gitlab.ow2.org/authzforce/core/blob/develop/pdp-engine/src/test/java/org/ow2/authzforce/core/pdp/impl/test/DefaultEnvironmentPropertiesTest.java#L36), I saw in the class javadoc:

```java
/**
 * 
 * Tests the placeholders replacement with {@link DefaultEnvironmentProperties} class.
 * <p>
 * WARNING: An environment variable AUTHZFORCE_DATA_DIR must be set to "/tmp/authzforce" for the test to succeed (e.g. with 'environmentVariables' configuration element of Maven Surefire plugin)
 */
```

What I did is:

```
export AUTHZFORCE_DATA_DIR=/tmp/authzforce
```

And relaunch PIT with:: `mvn org.pitest:pitest-maven:mutationCoverage`, and obtained:

```txt
================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : 8 seconds
> build mutation tests : 1 seconds
> run mutation analysis : 4 minutes and 13 seconds
--------------------------------------------------------------------------------
> Total  : 4 minutes and 23 seconds
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 1526 mutations Killed 181 (12%)
>> Ran 29471 tests (19.31 tests per mutation)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:26 min
[INFO] Finished at: 2019-02-26T13:45:00+01:00
[INFO] ------------------------------------------------------------------------
```

This means that the test suite requires this environment variable to be setted.

And then run DSpot with: `mvn dspot:amplify-unit-tests` and seems to work (for now).

Why the `mvn test` passes but not DSpot/PIT? Because the environment variable is configured only for surefire plugin:

```xml
<plugin>
<artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <skipTests>false</skipTests>
        <systemPropertyVariables> 
            <javax.xml.accessExternalSchema>all</javax.xml.accessExternalSchema>
        </systemPropertyVariables>
        <environmentVariables>
        <!-- Test environment variable for DefaultEnvironmentPropertiesTest class -->
            <AUTHZFORCE_DATA_DIR>/tmp/authzforce</AUTHZFORCE_DATA_DIR>           
        </environmentVariables>
        <properties>
            <property>
                <name>surefire.testng.verbose</name>
                <!-- verbosity level from 0 to 10 (10 is the most detailed), or -1 for debug. More info: http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html -->
                <value>3</value>
            </property>
        </properties>
        <includes>
            <include>**/MainTest.java</include>
        </includes>
    </configuration>
</plugin>
```

**Comment by gibello** [comment]
Some tests require an environment variable to be set (comment in authzforce/core/pdp/impl/test/DefaultEnvironmentPropertiesTest.java suggests that AUTHZFORCE_DATA_DIR must be set to "/tmp/authzforce", e.g. with 'environmentVariables' configuration element of Maven Surefire plugin).

If I set AUTHZFORCE_DATA_DIR (export AUTHZFORCE_DATA_DIR=/tmp/authzforce) prior to running "mvn dspot:amplify-unit-tests", the error does not occur.

As "mvn test" runs fine without setting any environment variable, there must be some env-related stuff that is not properly passed to DSpot (is it related to "Surefire plugin" or not, this has to be checked).
