### ISSUE TITLE
Cannot build dspot with Oracle JDK 11 -- use jacoco > v0.8.2

### ISSUE THREAD

**Issue by borisbaldassari** [STAMP-project/dspot#804]
#### Characteristics
- **Issue Type**: test report
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: Dspot
- **Execution Environment**: debian 9.9 with JDK Oracle 11.0.2
- **Reporter**: Boris Baldassari

#### Description

i've setup a jenkins job to build and test dspot, on a Debian 9.9 host with Java Oracle 11.0.2.
It is public: http://ci6.castalia.camp:8080/job/dspot/
When trying to compile and test the product I get the following error: 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
FATAL ERROR in native method: processing of -javaagent failed
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
Aborted
```
Full log can be seen at http://ci6.castalia.camp:8080/job/dspot/4/console

## Hint

There are [reports that Jacoco plays badly with Oracle JDK 11](https://github.com/vaskoz/core-java9-impatient/issues/11). The version of Jacoco that fixes this behaviour is the 0.8.2. When bumping the various jacoco deps to 0.8.2 in the main pom.xml file the tests pass and the builds goes further, but fails shortly after.

**Comment by borisbaldassari** [comment]
After bumping the version of the jacoco deps, the build actually starts but then fails with the following tests:

```
Tests in error: 
  GradleAutomaticBuilderTest.setUp:53 » IllegalArgument Could not determine java...
  GradleAutomaticBuilderTest.setUp:53 » IllegalArgument Could not determine java...
  GradleAutomaticBuilderTest.setUp:53 » IllegalArgument Could not determine java...
  GradleAutomaticBuilderTest.setUp:53 » IllegalArgument Could not determine java...
  MavenAutomaticBuilderTest.testFailingPit:99 » Runtime java.lang.RuntimeExcepti...
  DSpotMockedTest>AbstractTest.setUp:21 » Runtime java.lang.RuntimeException: ja...
  SimpleBudgetizerTest.test:63 » NullPointer

Tests run: 195, Failures: 3, Errors: 7, Skipped: 6

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DSpot - Parent ..................................... SUCCESS [  0.295 s]
[INFO] DSpot - Core ....................................... FAILURE [08:02 min]
[INFO] DSpot - Maven Plugin ............................... SKIPPED
[INFO] DSpot - Prettifier ................................. SKIPPED
[INFO] DSpot - Diff Test Selection ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:04 min
[INFO] Finished at: 2019-05-24T22:42:32+02:00
[INFO] Final Memory: 49M/167M
```

**Comment by borisbaldassari** [comment]
Can't reproduce anymore.. closing the issue.
