### ISSUE TITLE
Error: "Something bad happened during assertion amplification"

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#807]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot maven plugin 2.1.1-SNAPSHOT
- **Execution Environment**: Ubuntu Linux 18.04
- **Reporter**: Pierre-Yves Gibello, pyg@ow2.org

#### Description

A DSpot error occurs: "Something bad happened during assertion amplification"
with an exception stack (java.lang.RuntimeException: Forked process did not finished correctly)

Build is successful, but no amplified test is generated:
[INFO] The amplification ends up with 0 amplified test methods over 0 test classes.

#### Steps to reproduce

Tested on joram project ( https://gitlab.ow2.org/joram ).
Directory: joram/joram/mom/core

mvn eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests -Dtest=org.objectweb.joram.mom.proxies.MessageIdListImplEncodingTest -Diteration=1

The following error is displayed (and logged in target/dspot/output/report.txt):

```
[WARNING] DSpot encountered some errors during amplification.
[WARNING] DSpot encountered 1 error(s) during amplification.
Something bad happened during assertion amplification
java.lang.RuntimeException: Forked process did not finished correctly
	at eu.stamp_project.testrunner.EntryPoint.runGivenCommandLine(EntryPoint.java:417)
	at eu.stamp_project.testrunner.EntryPoint.runTests(EntryPoint.java:198)
	at eu.stamp_project.testrunner.EntryPoint.runTests(EntryPoint.java:193)
	at eu.stamp_project.testrunner.EntryPoint.runTests(EntryPoint.java:154)
	at eu.stamp_project.utils.execution.TestRunner.run(TestRunner.java:98)
	at eu.stamp_project.utils.execution.TestRunner.runGivenTestMethods(TestRunner.java:66)
	at eu.stamp_project.utils.compilation.TestCompiler.compileAndRun(TestCompiler.java:99)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.innerAssertionAmplification(AssertGenerator.java:111)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.assertionAmplification(AssertGenerator.java:76)
	at eu.stamp_project.dspot.Amplification.assertionsAmplification(Amplification.java:214)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:186)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:131)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:274)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$5(DSpot.java:255)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:256)
	at eu.stamp_project.Main.run(Main.java:65)
	at eu.stamp_project.DSpotMojo.execute(DSpotMojo.java:311)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by danglotb** [comment]
Hello @gibello 

I cannot reproduce the error on my side.

Could you provide the whole trace of the execution?

**Comment by gibello** [comment]
Hello @danglotb ,
See attached output:
[dspot.txt](https://github.com/STAMP-project/dspot/files/3231521/dspot.txt)
Thanks !

**Comment by danglotb** [comment]
Hi @gibello 

According to your logs, you are using `JacocoCoverageSelector` test-criterion:

> Some test(s) failed during computation of coverage:
run(org.objectweb.joram.mom.proxies.MessageIdListImplEncodingTest): org.objectweb.joram.mom.util.MessageIdListImpl cannot be cast to org.objectweb.joram.mom.util.MessageIdListImpl
File saved to the following path: /home/gibello/STAMP/joram-test/joram/joram/mom/core/target/dspot/CoveragePerTest.ser
Loading /home/gibello/STAMP/joram-test/joram/joram/mom/core/target/dspot/CoveragePerTest.ser
	[[1;34mINFO[m] Coverage per test methods has been computed 
	run: 61 / 46699

I tried to reproduce with:

`mvn eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests -Dtest=org.objectweb.joram.mom.proxies.MessageIdListImplEncodingTest -Diteration=1 -Dtest-criterion=JacocoCoverageSelector`

But I do not have the same error.

Please, provide me your complete configuration, including modifications of the `pom.xml`, if any.

Thank you.

**Comment by gibello** [comment]
Hi @danglotb ,
You are right, there is something missing to reproduce.
Add -Damplifiers=AllLiteralAmplifiers , for example as follows:

mvn eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests -Dtest=org.objectweb.joram.mom.proxies.MessageIdListImplEncodingTest -Damplifiers=AllLiteralAmplifiers -Diteration=1

No need to add anything to the pom (I just tried with a fresh joram clone), but there was something wrong in my config, as you guessed.

Let me know if you can reproduce now... and sorry for the incomplete report.
