### ISSUE TITLE
DSpot reads null for working-directory option in Maven

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#821]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: DSpot latest version published in Maven central
- **Execution Environment**: Jenkins over Centos 7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
I have a DSpot job configured in Jenkins that invokes DSpot using its Maven interface over Supersede IF component.
Jenkins freestyle job uses the Maven plugin to invoke DSpot. At the end the following Maven command is invoked:
`mvn -f ./IF/API/eu.supersede.if.api/pom.xml -s /var/jenkins_home/settings.xml eu.stamp-project:dspot-maven:amplify-unit-tests -Dworking-directory=./IF/API/eu.supersede.if.api/ -Dpath-to-properties=./dspot.properties -Diteration=3 -Dtest=eu.supersede.integration.api.adaptation.dashboard.proxies.test.AdaptationDashboardProxyTest -Damplifiers=MethodAdd,AllLiteralAmplifiers,MethodGeneratorAmplifier -Dtest-criterion=JacocoCoverageSelector -DtimeOut=30000 -Dmax-test-amplified=200 -Dbudgetizer=NoBudgetizer -Dclean -Dverbose `

In a previous job, dating on April, 9th, this jobs completed successfully, and in particular the property:
`working-directory=./IF/API/eu.supersede.if.api/` was read correctly, as I can see in the logs:
```
[INFO] Default: provided Maven automatic builder.
[INFO] Using /var/jenkins_home/workspace/supersede-if-dspot/./IF/API/eu.supersede.if.api/pom.xml to run maven.
[INFO] Using /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.0 for maven home
[INFO] run maven: /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.0/bin/mvn clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
```
However, in today job run, with same configuration, the property `working-directory=./IF/API/eu.supersede.if.api/` was read to null, so the dspot.properties was not read:
```
java.io.FileNotFoundException: ./dspot.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at eu.stamp_project.DSpotMojo.initializeProperties(DSpotMojo.java:305)
	at eu.stamp_project.DSpotMojo.execute(DSpotMojo.java:233)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Path to runner Classes: /root/.m2/repository/eu/stamp-project/test-runner/2.0.5/test-runner-2.0.5-jar-with-dependencies.jar
[INFO] /root/.m2/repository/org/jacoco/org.jacoco.core/0.7.9/org.jacoco.core-0.7.9.jar
[INFO] /root/.m2/repository/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
[INFO] /root/.m2/repository/eu/stamp-project/test-runner/2.0.5/test-runner-2.0.5-jar-with-dependencies.jar
[WARNING] : unknown automatic builder specified in configuration, going to default.
[INFO] Default: provided Maven automatic builder.
[INFO] Using /var/jenkins_home/workspace/supersede-if-dspot/null/pom.xml to run maven.
[INFO] Using /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.0 for maven home
[INFO] run maven: /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.0/bin/mvn clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
```
Is it a possible regression bug between the DSpot version by April and the recentest one?
Let me know if you need additional information about this issue. Unfortunately, I can not grant you access to our Jenkins, but I can provided you the complete job run logs, and configuration, if you need them. Configuration for the two job runs is  the same.

#### Steps to reproduce
See details above.
#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

In fact, using `2.1.0` result with the reported error. This has been fixed in the recent changes on the command line.

You can specify the version `2.1.1-SNAPSHOT` to use it.

It seems like a release is needed. I'm sorry I should schedule them.

Tell me if you are still encountering the issue.
