### ISSUE TITLE
test-projects.properties file not found when running the provided example

### ISSUE THREAD

**Issue by danivb** [STAMP-project/dspot#919]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
 **Tool/Service/Component**: dspot, 2.2.1
- **Execution Environment**: Centos 7
- **Reporter**: Daniel Villacis, daniel.villacisbarona@harmonicinc.com

#### Description
The provided example ```--example``` cannot be executed due to ```test-projects.properties```  does not exist.
JAVA_HOME and MAVEN_HOME have been configured as explained in the documentation.

#### Steps to reproduce
- Download dspor 2.2.1 version
- run ```java -jar target/dspot-2.2.1-jar-with-dependencies.jar --example```
- Result: 
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/test-projects/test-projects.properties (No such file or directory)
at eu.stamp_project.utils.options.Configuration.configureExample(Configuration.java:38)
at eu.stamp_project.utils.options.JSAPOptions.parse(JSAPOptions.java:47)
at eu.stamp_project.Main.main(Main.java:38)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/test-projects/test-projects.properties (No such file or directory)
at eu.stamp_project.utils.options.Configuration.loadProperties(Configuration.java:311)
at eu.stamp_project.utils.program.InputConfiguration.initialize(InputConfiguration.java:58)
at eu.stamp_project.utils.options.Configuration.configureExample(Configuration.java:30)
... 2 more
Caused by: java.io.FileNotFoundException: src/test/resources/test-projects/test-projects.properties (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at eu.stamp_project.utils.options.Configuration.loadProperties(Configuration.java:307)
```

##### Command Line / Options
```shell
java -jar target/dspot-2.2.1-jar-with-dependencies.jar --example
```

**Comment by danglotb** [comment]
Hello @danivb 

Thank you for reporting this. I'm looking into it.
